secrets:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  encrypted_key: <%= ENV["ENCRYPTED_KEY"] %>
  webhook_jwt_secret: <%= ENV.fetch('WEBHOOK_JWT_SECRET', 'jwt_secret') %>
  campaign_join_secret_token: <%= ENV.fetch('CAMPAIGN_JOIN_SECRET_TOKEN', 'jwt_secret') %>
  oac:
    client_id: <%= ENV.fetch('OAC_OAUTH_CLIENT_ID', nil) %>
    client_secret: <%= ENV.fetch('OAC_OAUTH_CLIENT_SECRET', nil) %>
  import_export_secret: <%= ENV.fetch('IMPORT_EXPORT_SECRET', nil) %>
  rack_timeout:
    service_timeout: false
    wait_timeout: false
    wait_overtime: false
    service_past_wait: false
  secret_token_for_generate: <%= ENV["SECRET_TOKEN_FOR_GENERATE"] %>
  power_bi:
    tenant_id: <%= ENV.fetch('POWER_BI_TENANT_ID', nil) %>
    client_id: <%= ENV.fetch('POWER_BI_CLIENT_ID', nil) %>
    client_secret: <%= ENV.fetch('POWER_BI_CLIENT_SECRET', nil) %>
    group_id: <%= ENV.fetch('POWER_BI_GROUP_ID', nil) %>
  twilio:
    account_sid: <%= ENV.fetch('TWILIO_ACCOUNT_ID', nil) %>
    from_mobile_no: <%= ENV.fetch('TWILIO_FROM_MOBILE_NO', nil) %>
    api_key: <%= ENV.fetch('TWILIO_API_KEY', nil) %>
    api_secret: <%= ENV.fetch('TWILIO_API_SECRET', nil) %>
    verification_service_sid: <%= ENV.fetch('TWILIO_VERIFY_SERVICE_ID', nil) %>
  examus:
    url: <%= ENV.fetch('EXAMUS_URL', 'https://stage.proctor.alemira.com') %>
    integration_name: <%= ENV.fetch('EXAMUS_INTEGRATION_NAME', 'ttedev') %>
    jwt_secret: "<%= ENV['EXAMUS_JWT_SECRET'] %>"
  faas:
    signing_secret: <%= ENV.fetch('FAAS_SIGNING_SECRET', 'secret') %>
  oci:
    functions:
      url_to_pdf: <%= ENV.fetch('OCI_URL_TO_PDF_INVOKE_ENDPOINT', nil) %>
      zip_s3_files: <%= ENV.fetch('OCI_ZIP_S3_FILES_INVOKE_ENDPOINT', nil) %>
    user: <%= ENV.fetch('OCI_USER_ID', nil) %>
    tenancy: <%= ENV.fetch('OCI_TENANCY', nil) %>
    private_key: |
      <%= ENV.fetch('OCI_PRIVATE_KEY', '').gsub("\n", "\n      ") %>
    fingerprint: <%= ENV.fetch('OCI_FINGERPRINT', nil) %>
    compartment_id: <%= ENV.fetch('OCI_COMPARTMENT_ID', nil) %>
    genai_region: <%= ENV.fetch('GENAI_OCI_REGION', nil) %>
  aws:
    config:
      access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
      secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
      region: <%= ENV["AWS_REGION"] %>
    lambda:
      url_to_pdf:
        url: <%= ENV.fetch('URL_TO_PDF_LAMBDA_URL', nil) %>
        sqs_url: <%= ENV.fetch('URL_TO_PDF_SQS_URL', nil) %>
        priority_sqs_url: <%= ENV.fetch('URL_TO_PDF_PRIORITY_SQS_URL', nil) %>
      zip_s3_files:
        url: <%= ENV.fetch('ZIP_S3_FILES_LAMBDA_URL', nil) %>
        sqs_url: <%= ENV.fetch('ZIP_S3_FILES_SQS_URL', nil) %>
  saville:
    wsdl_url: <%= ENV.fetch('SAVILLE_WSDL_URL', 'https://tte-lighthouse.uat-oasys.com/ws/integration/savillehrxml/Assessment.asmx?WSDL') %>
    credential:
      user_name: <%= ENV["SAVILLE_USER_NAME"] %>
      password: <%= ENV["SAVILLE_PASSWORD"] %>
      client_code: <%= ENV["SAVILLE_CLIENT_CODE"] %>
  pearson:
    base_api_url: <%= ENV["PEARSON_BASE_API_URL"] %>
    credentials:
      api_key: <%= ENV["PEARSON_API_KEY"] %>
      user_name: <%= ENV["PEARSON_USER_NAME"] %>
      password: <%= ENV["PEARSON_PASSWORD"] %>
  simulation:
    base_api_url: <%= ENV.fetch('SIMULATION_BASE_API_URL', nil) %>
    frontend_base_url: <%= ENV.fetch('SIMULATION_FRONTEND_BASE_URL', nil) %>
    credentials:
      api_key: <%= ENV.fetch('SIMULATION_API_KEY', nil) %>
      shared_secret: <%= ENV.fetch('SIMULATION_SHARED_SECRET', nil) %>
  hogan:
    default_provider:  <%= ENV.fetch('HOGAN_DEFAULT_PROVIDER', 'mercer') %>
    credentials:
      phoenix:
        client_id: <%= ENV["HOGAN_PHOENIX_CLIENT_ID"] %>
        client_user_id: <%= ENV["HOGAN_PHOENIX_CLIENT_USER_ID"] %>
        client_password: <%= ENV["HOGAN_PHOENIX_CLIENT_PASSWORD"] %>
        master_client_id: <%= ENV["HOGAN_PHOENIX_MASTER_CLIENT_ID"] %>
      mentis:
        client_id: <%= ENV["HOGAN_MENTIS_CLIENT_ID"] %>
        client_user_id: <%= ENV["HOGAN_MENTIS_CLIENT_USER_ID"] %>
        client_password: <%= ENV["HOGAN_MENTIS_CLIENT_PASSWORD"] %>
        master_client_id: <%= ENV["HOGAN_MENTIS_MASTER_CLIENT_ID"] %>
      mercer:
        client_id: <%= ENV["HOGAN_MERCER_CLIENT_ID"] %>
        client_user_id: <%= ENV["HOGAN_MERCER_CLIENT_USER_ID"] %>
        client_password: <%= ENV["HOGAN_MERCER_CLIENT_PASSWORD"] %>
        master_client_id: <%= ENV["HOGAN_MERCER_MASTER_CLIENT_ID"] %>
    login_url: <%= ENV["HOGAN_LOGIN_URL"] %>
    wsdl_api_url: <%= ENV["HOGAN_WSDL_BASE_URL"] %>
    json_api_url: <%= ENV["HOGAN_JSON_BASE_URL"] %>
    encrypted_key: <%= ENV["HOGAN_ENCRYPTED_KEY"] %> # SecureRandom.base64(32)
  http_auth: <%= ENV["HTTP_AUTH_CREDENTIALS"] %>
  chrome_path: google-chrome
  s3_compatible_storage:
    endpoint: <%= ENV["S3_COMPATIBLE_STORAGE_ENDPOINT"] %>
    access_key_id: <%= ENV["S3_COMPATIBLE_STORAGE_ACCESS_KEY_ID"] %>
    secret_access_key: <%= ENV["S3_COMPATIBLE_STORAGE_SECRET_ACCESS_KEY"] %>
    region: <%= ENV.fetch("S3_COMPATIBLE_STORAGE_REGION", 'eu-west-1') %>
    public_bucket: <%= ENV["S3_COMPATIBLE_STORAGE_PUBLIC_BUCKET"] %>
    private_bucket: <%= ENV["S3_COMPATIBLE_STORAGE_PRIVATE_BUCKET"] %>
    dailyco_bucket: <%= ENV["S3_COMPATIBLE_STORAGE_DAILYCO_BUCKET"] %>
    yoodli_reports_bucket: <%= ENV.fetch("S3_COMPATIBLE_STORAGE_YOODLI_REPORTS_BUCKET", 'yoodli-reports') %>
    provider: <%= ENV["S3_COMPATIBLE_STORAGE_PROVIDER"] %>
  daily_co:
    v1:
      domain_id: <%= ENV["DAILY_CO_V1_DOMAIN_ID"] %>
      api_key: <%= ENV["DAILY_CO_V1_API_KEY"] %>
      subdomain: <%= ENV["DAILY_CO_V1_SUBDOMAIN"] %>
    v2:
      domain_id: <%= ENV["DAILY_CO_V2_DOMAIN_ID"] %>
      api_key: <%= ENV["DAILY_CO_V2_API_KEY"] %>
      subdomain: <%= ENV["DAILY_CO_V2_SUBDOMAIN"] %>
    assume_role_arn: <%= ENV["DAILY_CO_ASSUME_ROLE_ARN"] %>
