# frozen_string_literal: true

require 'deepl'

module Devtools
  module CLI
    module Commands
      module I18n
        class AutoTranslateXlsx < Base
          desc 'Automatically translate English text in an XLSX file to other languages using DeepL'
          option :file_path,
                 desc: 'Path to the XLSX file containing translations (generated by translation_changes command)',
                 required: true,
                 alias: :fp
          option :skip_if_exist,
                 desc: 'Skip translating cells that already have content (default: false)',
                 type: :boolean,
                 default: false,
                 alias: :sie
          option :output_file,
                 desc: 'Path to save the output XLSX file (optional)',
                 default: nil,
                  alias: :of

          # Mapping of locale codes to DeepL target language codes
          LOCALE_MAPPING = {
            ar: 'AR', # Arabic
            bg: 'BG', # Bulgarian
            cs: 'CS', # Czech
            da: 'DA', # Danish
            de: 'DE', # German
            el: 'EL', # Greek
            en: 'EN', # English (unspecified variant)
            'en-GB': 'EN-GB', # English (British)
            'en-US': 'EN-US', # English (American)
            es: 'ES', # Spanish
            'es-ES': 'ES', # Spanish (Spain)
            et: 'ET', # Estonian
            fi: 'FI', # Finnish
            fr: 'FR', # French
            he: 'HE', # Hebrew
            hu: 'HU', # Hungarian
            id: 'ID', # Indonesian
            it: 'IT', # Italian
            ja: 'JA', # Japanese
            ko: 'KO', # Korean
            lt: 'LT', # Lithuanian
            lv: 'LV', # Latvian
            nb: 'NB', # Norwegian Bokmål
            nl: 'NL', # Dutch
            pl: 'PL', # Polish
            pt: 'PT', # Portuguese (unspecified variant)
            'pt-BR': 'PT-BR', # Portuguese (Brazilian)
            'pt-PT': 'PT-PT', # Portuguese (excluding Brazilian)
            ro: 'RO', # Romanian
            ru: 'RU', # Russian
            sk: 'SK', # Slovak
            sl: 'SL', # Slovenian
            sv: 'SV', # Swedish
            th: 'TH', # Thai
            tr: 'TR', # Turkish
            uk: 'UK', # Ukrainian
            vi: 'VI', # Vietnamese
            zh: 'ZH', # Chinese (unspecified variant)
            'zh-Hans': 'ZH-HANS', # Chinese (simplified)
            'zh-Hant': 'ZH-HANT', # Chinese (traditional),
            'zh-HK': 'ZH-HANT' # Chinese (Hong Kong)
          }.freeze

          def call(file_path:, skip_if_exist: false, output_file: nil, **)
            @file_path = file_path
            @skip_if_exist = skip_if_exist
            @output_file = output_file

            display_header
            validate_input_file
            validate_deepl_auth_key

            begin
              process_translations
            rescue StandardError => e
              handle_error(e)
            end
          end

          private

          def process_translations
            worksheet = prepare_worksheet
            translation_metadata = analyze_file_structure(worksheet)
            perform_translations(worksheet, translation_metadata)
            save_results
            display_success_message
          end

          def prepare_worksheet
            workbook, worksheet = open_xlsx_file
            @workbook = workbook
            worksheet
          end

          def analyze_file_structure(worksheet)
            headers = get_headers(worksheet)
            english_col_index = find_english_column(headers)

            locale_columns = identify_locale_columns(headers)
            validate_translatable_columns(locale_columns)

            {
              headers: headers,
              english_col_index: english_col_index,
              locale_columns: locale_columns
            }
          end

          def find_english_column(headers)
            english_col_index = headers.index('English / en')
            unless english_col_index
              cli_error "Error: Could not find 'English / en' column in the XLSX file"
            end

            english_col_index
          end

          def validate_translatable_columns(locale_columns)
            if locale_columns.empty?
              cli_log 'No translatable locale columns found in the file.'
              exit(0)
            end
          end

          def perform_translations(worksheet, metadata)
            translate_rows(worksheet, metadata[:english_col_index], metadata[:locale_columns])
          end

          def save_results
            output_path = generate_output_path
            save_workbook(@workbook, output_path)
            @output_path = output_path
          end

          def display_success_message
            cli_log 'Translation completed successfully!'
            cli_log "Auto translated file: #{@output_path}"
          end

          def handle_error(error)
            cli_error "Error during translation process: #{error.message}"
            cli_error error.backtrace.join("\n") if ENV['DEBUG']
          end

          def display_header
            cli_log "\nAutomatic XLSX Translation using DeepL"
            cli_log "====================================\n\n"
          end

          def validate_input_file
            unless File.exist?(@file_path)
              cli_error "Error: File not found at path #{@file_path}"
            end

            unless @file_path.end_with?('.xlsx')
              cli_error "Error: File must be an XLSX file (got #{@file_path})"
            end
          end

          def validate_deepl_auth_key
            if ENV['DEEPL_AUTH_KEY'].nil? || ENV['DEEPL_AUTH_KEY'].strip.empty?
              cli_error 'Error: DEEPL_AUTH_KEY environment variable is not set. DeepL translation requires an API key.'
            end
          end

          def open_xlsx_file
            cli_log "Opening XLSX file: #{@file_path}"
            workbook = Roo::Excelx.new(@file_path)
            worksheet = workbook.sheet(0)

            [workbook, worksheet]
          end

          def get_headers(worksheet)
            worksheet.row(1)
          end

          def identify_locale_columns(headers)
            locale_columns = {}
            cli_log 'Analyzing file structure for translatable columns...'

            headers.each_with_index do |header, index|
              locale_info = extract_locale_info(header, index)
              next unless locale_info

              if locale_info[:supported]
                locale_columns[index] = locale_info
                cli_log "Found translatable column: #{locale_info[:name]} (#{locale_info[:code]})" if ENV['DEBUG']
              elsif locale_info[:code] != 'en'
                cli_log "Skipping unsupported locale: #{locale_info[:name]} (#{locale_info[:code]})"
              end
            end

            cli_log "Found #{locale_columns.size} translatable columns"
            locale_columns
          end

          def extract_locale_info(header, index)
            # Match headers like "Arabic / ar", "French / fr", etc.
            return nil unless header.is_a?(String)

            match = header.match(%r{([a-zA-Z\(\) ]+) / ([a-z]{2}(?:-[A-Z]{2})?)$})
            return nil unless match

            language_name = match[1].strip
            locale_code = match[2].strip

            {
              index: index,
              name: language_name,
              code: locale_code,
              deepl_code: get_deepl_code(locale_code),
              supported: supported_by_deepl?(locale_code)
            }
          end

          def supported_by_deepl?(locale_code)
            return false unless locale_code
            return false if locale_code == 'en' # Skip English source language

            LOCALE_MAPPING.key?(locale_code.to_sym) || LOCALE_MAPPING.value?(locale_code.upcase)
          end

          def get_deepl_code(locale_code)
            return nil unless locale_code

            LOCALE_MAPPING[locale_code.to_sym] || locale_code.upcase
          end

          def translate_rows(worksheet, english_col_index, locale_columns)
            row_count = worksheet.last_row

            load_worksheet_data(worksheet, row_count)

            total_translations = translate_worksheet_data(row_count, english_col_index, locale_columns)

            cli_log "Translation complete. Translated #{total_translations} cells."
          end

          def load_worksheet_data(worksheet, row_count)
            cli_log 'Loading data from worksheet...'
            @translated_data = []

            # Read all rows from the original worksheet
            (1..row_count).each do |row_num|
              @translated_data << worksheet.row(row_num)
            end

            cli_log "Loaded #{row_count} rows from worksheet"
          end

          def translate_worksheet_data(row_count, english_col_index, locale_columns)
            cli_log 'Starting translation process...'
            translated_count = 0
            headers = @translated_data[0] # Get headers from the first row

            # Skip header row (1) and start from row 2 for translations
            (2..row_count).each do |row_num|
              row_index = row_num - 1 # Adjust for 0-based array
              row = @translated_data[row_index]
              english_text = row[english_col_index]

              # Skip if the text is empty or if it's a deleted key
              next if empty_text?(english_text) || deleted_key?(row, headers)

              translated_count += translate_row(row_index, english_text, locale_columns, translated_count)
            end

            translated_count
          end

          def empty_text?(text)
            text.nil? || text.to_s.strip.empty?
          end

          def translate_row(row_index, english_text, locale_columns, translated_count)
            row_translations = 0

            locale_columns.each do |col_index, locale_info|
              # Skip if cell already has content and skip_if_exist is true
              if @skip_if_exist && !empty_text?(@translated_data[row_index][col_index])
                cli_log "Skipping existing translation for #{locale_info[:name]}" if ENV['DEBUG']
                next
              end
              translation = translate_cell(english_text, locale_info[:deepl_code])
              next unless translation

              @translated_data[row_index][col_index] = translation
              row_translations += 1

              total_translations = translated_count + row_translations
              if (total_translations % 10).zero?
                cli_log "Traversed #{total_translations} cells..."
              end
            end

            row_translations
          end

          def translate_cell(text, target_language)
            translate_text(text, target_language)
          end

          def translate_text(text, target_language)
            return nil if empty_text?(text)

            begin
              with_retry(max_attempts: 3, delay: 2) do
                translator = TranslateString.new
                translator.call(
                  string: text,
                  target_language: target_language,
                  source_language: 'en',
                  preserve_formatting: true,
                  translation_provider: 'microsoft',
                  no_log: false
                )
              end
            rescue StandardError => e
              handle_translation_error(e, target_language)
              nil
            end
          end

          def extract_interpolation_variables(text)
            variables = []
            text.scan(/%\{([^}]+)\}/) do |match|
              variables << match[0]
            end
            variables
          end

          def with_retry(max_attempts: 3, delay: 2)
            attempts = 0

            begin
              attempts += 1
              yield
            rescue StandardError => e
              if attempts < max_attempts
                cli_log "API call failed (attempt #{attempts}/#{max_attempts}), retrying in #{delay} seconds..."
                sleep delay
                retry
              else
                raise e
              end
            end
          end

          def handle_translation_error(error, target_language)
            cli_log "Warning: Failed to translate text to #{target_language}. Error: #{error.message}"
          end

          def generate_output_path
            if @output_file
              FileUtils.mkdir_p(File.dirname(@output_file))
              @output_file
            else
              dir = File.dirname(@file_path)
              basename = File.basename(@file_path, '.xlsx')
              timestamp = current_time_stamp
              "#{dir}/#{basename}_translated_#{timestamp}.xlsx"
            end
          end

          def save_workbook(_workbook, output_path)
            cli_log "Saving translated XLSX file to: #{output_path}"

            begin
              ensure_output_directory(output_path)
              create_excel_file(output_path)

              unless File.exist?(output_path)
                cli_error "Error: Failed to create output file at #{output_path}"
              end
            rescue StandardError => e
              cli_error "Error saving file: #{e.message}"
              cli_error e.backtrace.join("\n") if ENV['DEBUG']
            end
          end

          def ensure_output_directory(output_path)
            output_dir = File.dirname(output_path)
            FileUtils.mkdir_p(output_dir) unless File.directory?(output_dir)
          end

          def create_excel_file(output_path)
            workbook = FastExcel.open(output_path, constant_memory: true)
            worksheet = workbook.add_worksheet('Translations')
            header_style = workbook.bold_format
            write_data_to_worksheet(worksheet, header_style)
            workbook.close
          rescue LoadError => e
            cli_error 'Error: fast_excel gem not found or not properly loaded'
            raise e
          rescue StandardError => e
            cli_error "Error while creating Excel file: #{e.message}"
            raise e
          end

          def write_data_to_worksheet(worksheet, header_style)
            row_count = @translated_data.size
            @translated_data.each_with_index do |row, index|
              if index.zero?
                worksheet.append_row(row, header_style)
              else
                worksheet.append_row(row)
              end

              if row_count > 100 && (index % 50).zero?
                cli_log "Wrote #{index} of #{row_count} rows..."
              end
            rescue StandardError => e
              cli_error "Error writing row #{index}: #{e.message}"
              cli_error "Row data: #{row.inspect}" if ENV['DEBUG']
              raise e
            end
          end

          def deleted_key?(row, headers)
            action_index = headers.index('Action')
            return false unless action_index

            action = row[action_index]
            action == 'deleted'
          end
        end
      end
    end
  end
end
