env:
  AGILE_ASSETS_URL: "https://static.tte-lighthouse.com/interactive-assessments/"
  APP_DOMAIN: "tte-lighthouse.ae"
  APP_PROTOCOL: "https"
  APP_SUB_DOMAIN: "www"
  ASSET_HOST: "https://a.tte-lighthouse.ae"
  AWS_REGION: "eu-west-1"
  AWS_S3_ACCELERATION_ENABLED: "false"
  AWS_S3_BUCKET: "psychometrics-uae"
  DISABLE_SAML_FOR_ADMINS: "true"
  EMAILS_FOR_DEPLOYMENT_TASK: "shuja@thetalententerprise.com, rohan@thetalententerprise.com"
  EXAMUS_URL: "https://bahrain.proctor.alemira.com"
  HOGAN_JSON_BASE_URL: "https://www.assessmentlink.com/HasStandardApi"
  HOGAN_LOGIN_URL: "https://www.assessmentlink.com/mercer/participant/Login.aspx"
  HOGAN_WSDL_URL: "https://www.assessmentlink.com/HASSTDWS/HASAssessmentService.asmx?WSDL"
  INLINE_TRANSLATION_ENABLED: "true"
  JEMALLOC_ENABLED: "true"
  LANG: "en_US.UTF-8"
  MAIL_DOMAIN: "smtp.azurecomm.net"
  MAIL_ADDRESS: "smtp.azurecomm.net"
  MAIL_PORT: 587
  MAIL_AUTH_TYPE: "login"
  MALLOC_ARENA_MAX: "2"
  MIN_NETWORK_UPLOAD: "2"
  NEW_CAMPAIGN_ENABLED: "true"
  RACK_ENV: "production"
  RAILS_ENV: "production"
  RAILS_LOG_TO_STDOUT: "enabled"
  RAILS_MAX_THREADS: "5"
  RAILS_SERVE_STATIC_FILES: "enabled"
  REAL_ENV: "production-uae"
  SAVILLE_WSDL_URL: "https://tte-lighthouse.sc-oasys.com/ws/integration/savillehrxml/Assessment.asmx?WSDL"
  SENTRY_URL: "https://0ead9b13d2474ae49f62a3842e7b2631@o111210.ingest.sentry.io/1490001"
  SERVER_NAME: "PROD-AE"
  SIDEKIQ_CONCURRENCY: "12"
  SMTP_ENABLED: "true"
  TWO_FACTOR_AUTHENTICATION_ENABLED: "true"
  TZ: "Asia/Dubai"
  WEBHOOKS_ENABLED: "true"
  WEB_CONCURRENCY: "12"
  PORT: "3030"
  PEARSON_BASE_API_URL: "https://api.eu.connect.talentlens.com"
  TWILIO_FROM_MOBILE_NO: "+16319194059"
  TWILIO_VERIFY_SERVICE_ID: "VAa8d71bcbba8d941aeb95be2b7fc549d9"
  URL_TO_PDF_SQS_URL: "https://sqs.me-central-1.amazonaws.com/610814206204/prod-uaeUrlToPdfStdQueue"
  URL_TO_PDF_PRIORITY_SQS_URL: "https://sqs.me-central-1.amazonaws.com/610814206204/prod-uaeUrlToPdfPriorityStdQueue"
  URL_TO_PDF_FAAS_ENABLED: "true"
  # MAINTENANCE_START_DATETIME: "2022-10-07 17:00:00 +0400"
  # MAINTENANCE_DURATION: "30"
  DISABLE_TERSER: "true"
  PK_ID_START: "1000000000"
  S3_COMPATIBLE_STORAGE_PROVIDER: "aws"
  S3_COMPATIBLE_STORAGE_ENDPOINT: "https://s3.me-central-1.amazonaws.com"
  S3_COMPATIBLE_STORAGE_PUBLIC_BUCKET: "psychometrics-uae"
  S3_COMPATIBLE_STORAGE_PRIVATE_BUCKET: "psychometrics-uae"
  S3_COMPATIBLE_STORAGE_REGION: "me-central-1"
  PUBLIC_BUCKET_STORAGE_SERVICE_KEY: "s3_public_bucket"
  PRIVATE_BUCKET_STORAGE_SERVICE_KEY: "s3_private_bucket"
  ZIP_S3_FILES_FAAS_ENABLED:  "true"
  ZIP_S3_FILES_SQS_URL: "https://sqs.me-central-1.amazonaws.com/610814206204/prod-uaeZipS3FilesStdQueue"
  # FILE_HOST: "s3.tte-lighthouse.ae"
  CSP_REPORT_ONLY: "false"
  DAILY_CO_DOMAIN_ID: "b8fb3e7b-06ed-414f-8974-01d17b6f46e1"
  DAILY_CO_SUBDOMAIN: "tte"
  PROCTORING_ENABLED: "true"
  SIMULATION_BASE_API_URL: https://simulations.tte-lighthouse.ae
  SIMULATION_FRONTEND_BASE_URL: https://sims.tte-lighthouse.ae
