version: 2
jobs:
  build:
    working_directory: ~/psychometrics

    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: circleci/postgres:10.3-alpine
      - image: redis:4.0.9-alpine

    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - psychometrics-bundle-{{ checksum "Gemfile.lock" }}
            - psychometrics-bundle

      # Bundle set https true
      - run:
          name: Bundle set https true
          command: bundle config github.https true

      # Bundle install dependencies
      - run:
          name: Bundle
          command: bundle install --path vendor/bundle

      - run:
          name: Install phantomjs
          command: sudo curl --output /usr/local/bin/phantomjs https://s3.amazonaws.com/circle-downloads/phantomjs-2.1.1

      - run:
          name: Install psql
          command: sudo apt update && sudo apt install postgresql-client

      # Store bundle cache
      - save_cache:
          key: psychometrics-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Prepare DB connection info
      - run:
          name: Copy database.yml
          command: cp config/database.ci.yml config/database.yml

      # Prepare Web packer connection info
      - run:
          name: Copy secrets.yml
          command: cp config/secrets.ci.yml config/secrets.yml

      # Prepare application environment variables
      - run:
          name: Copy application.yml
          command: cp config/application.sample.yml config/application.yml

      # Database setup
      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:structure:load

      # Run tests in parallel (Rspec for now)
      - run:
          name: Rspec
          command: bundle exec rake

      # Save artifacts
      - store_artifacts:
          path: /tmp/test-results

      - store_artifacts:
          path: tmp/capybara

      - store_artifacts:
          path: coverage
