export default {
  Text: {
    sourceType: 'Text',
    position: {
      left: 100,
      top: 100,
      width: 650,
      height: 200,
    },
    style: {
      fontColor: '#333333',
      fontWeight: 'normal',
      fontStyle: 'normal',
      fontSize: '100%',
      fontFamily: '',
      verticalAlign: '',
      horizontalAlign: '',
      textAlign: '',
      alignItems: '',
      color: '#333333',
      borderColor: {
        r: '170',
        g: '170',
        b: '170',
        a: '1',
      },
    },
    zIndex: 3000,
    text: 'Double Click to Edit Text...',
  },

  Image: {
    position: {
      left: 100,
      top: 100,
      width: 650,
      height: 200,
    },
    sourceType: 'SimpleImage',
    style: {},
    url: '',
    zIndex: 3000,
    showOnAllPages: false,
  },

  Shape: {
    shapeType: 'Shape',
    position: {
      left: 100,
      top: 100,
      width: 650,
      height: 200,
    },
    style: {
      borderColor: {
        r: '170',
        g: '170',
        b: '170',
        a: '1',
      },
      backgroundColor: {
        r: '238',
        g: '238',
        b: '238',
        a: '1',
      },
    },
    zIndex: 3000,
    showOnAllPages: false,
  },

  Graph: {
    colors: [
      { id: 1, color: '#4572A7' },
      { id: 2, color: '#AA4643' },
      { id: 3, color: '#89A54E' },
      { id: 4, color: '#71588F' },
      { id: 5, color: '#4198AF' },
      { id: 6, color: '#DB843D' },
      { id: 7, color: '#93A9CF' },
      { id: 8, color: '#D19392' },
      { id: 9, color: '#B9CD96' },
      { id: 10, color: '#A99BBD' },
    ],
    choicesTexts: {},
    position: {
      left: 100,
      top: 100,
      width: 650,
      height: 250,
    },
    style: {
      fontColor: '#000000',
      fontSize: '100%',
      fontFamily: 'Arial',
      color: '#000000',
    },
    legendStyle: {
      fontColor: '#000000',
      fontSize: '100%',
      fontFamily: 'Arial',
      color: '#000000',
    },
    source: null,
    type: null,
    zIndex: 3000,
    barGradient: {
      enabled: false,
      startColor: 'var(--ant-primary-6)',
      endColor: 'var(--ant-primary-1)',
      direction: 'top_to_bottom',
    },
    showValues: true,
    showValuesInsideBar: false,
    showOnAllPages: false,
  },

  Table: {
    choicesTexts: {},
    type: 'SimpleTable',
    columnsCount: 2,
    rowsCount: 2,
    itemsPerPage: 10,
    pageNumber: 1,
    minPosition: 1,
    maxPosition: 5,
    leftPanelColor: '#000',
    columnData: null,
    rowData: null,
    defaultCell: {
      value: '',
      styles: {

      },
    },
    position: {
      left: 100,
      top: 100,
      width: 650,
      height: 200,
    },
    style: {
      fontSize: '100%',
      fontFamily: 'Arial',
      width: '100%',
    },
    zIndex: 3000,
    showOnAllPages: false,
    defaultTableColumns: null,
    tableColumns: null,
  },
}
