
# APP_DOMAIN: lvh.me
# APP_PROTOCOL: http
# APP_SUB_DOMAIN: www
# HTTP_AUTH_CREDENTIALS:

HASHIDS_SALT: 'fake_salt'
# ENCRYPTED_KEY:
# SECRET_KEY_BASE:
# SECRET_TOKEN_FOR_GENERATE:

MAIL_USERNAME: 'fake_username'
MAIL_PASSWORD: 'fake_password'
MAIL_DOMAIN: 'fake.domain.com'
MAIL_ADDRESS: provider.address.com
# MAIL_PORT: 587

# AWS_ACCESS_KEY_ID:
# AWS_REGION:
# AWS_S3_BUCKET:
# AWS_SECRET_ACCESS_KEY:

MINDMILL_KEY: 'fake_key'
# MINDMILL_PREFIX:

# HOGAN_CLIENT_ID:
# HOGAN_CLIENT_USER_ID:
# HOGAN_CLIENT_PASSWORD:
# HOGAN_LOGIN_URL:
# HOGAN_WSDL_URL:
# HOGAN_ENCRYPTED_KEY:

# REDIS_URL:
# REDIS_PROVIDER: REDIS_URL

# PIPELINE_STAGE:
# RACK_ENV: 
# RAILS_ENV:
# RAILS_LOG_TO_STDOUT:
# RAILS_SERVE_STATIC_FILES:

# BUNDLE_DISABLE_EXEC_LOAD: true
# BUNDLE_GITHUB__HTTPS: true
# BUNDLE_GITLAB__COM:

# SENTRY_URL: