development:
  adapter: async

test:
  adapter: async

staging:
  adapter: redis
  url: 'redis://localhost:6379/1'
  path: '/var/run/redis/redis.sock'
  db: 1
  channel_prefix: psychometrics_staging

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] || 'redis://localhost:6379/1' %>
  path: '/var/run/redis/redis.sock'
  db: 1
  channel_prefix: psychometrics_production
