default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  host: postgres
  username: postgres
  password: postgres

test:
  <<: *default
  database: circle_test

