<% require './lib/i18n_csv_tasks' %>

<% require './lib/custom_js_tsx_scanner' %>

# i18n-tasks finds and manages missing and unused translations: https://github.com/glebm/i18n-tasks

# The "main" locale.
base_locale: en
## All available locales are inferred from the data by default. Alternatively, specify them explicitly:
# locales: [es, fr]
## Reporting locale, default: en. Available: en, ru.
# internal_locale: en

# Read and write translations.
data:
  ## Translations are read from the file system. Supported format: YAML, JSON.
  ## Provide a custom adapter:
  # adapter: I18n::Tasks::Data::FileSystem

  # Locale files or `File.find` patterns where translations are read from:
  read:
    ## Default:
    # - config/locales/%{locale}.yml
    ## More files:
     - config/locales/%{locale}/*.yml
    ## Another gem (replace %#= with %=):
    # - "<%#= %x[bundle show vagrant].chomp %>/templates/locales/%{locale}.yml"

  # Locale files to write new keys to, based on a list of key pattern => file rules. Matched from top to bottom:
  # `i18n-tasks normalize -p` will force move the keys according to these rules
  write:
    ## For example, write devise and simple form keys to their respective files:
    # - ['{devise, simple_form}.*', 'config/locales/\1.%{locale}.yml']
    ## Catch-all default:
    # - config/locales/%{locale}.yml
    - ['administration.*', 'config/locales/%{locale}/administration.yml']
    - ['privacy_policy.*', 'config/locales/%{locale}/policy.yml']
    - ['privacy_notice.marsh', 'config/locales/%{locale}/privacy_notice_marsh.yml']
    - ['privacy_notice.mercer_a_marsh_business', 'config/locales/%{locale}/privacy_notice_mercer_a_marsh_business.yml']
    - ['privacy_notice.*', 'config/locales/%{locale}/privacy_notice.yml']
    - ['cookies_notice', 'config/locales/%{locale}/cookies_notice.yml']
    - ['dry_errors.*', 'config/locales/%{locale}/dry_errors.yml']
    - ['admin.*', 'config/locales/%{locale}/admin.yml']
    - ['shared.*', 'config/locales/%{locale}/shared.yml']
    - ['enduser.*', 'config/locales/%{locale}/enduser.yml']
    - config/locales/%{locale}/others.yml

  ## Specify the router (see Readme for details). Valid values: conservative_router, pattern_router, or a custom class.
  # router: convervative_router

  yaml:
    write:
      # do not wrap lines at 80 characters
      line_width: -1

  ## Pretty-print JSON:
  # json:
  #   write:
  #     indent: '  '
  #     space: ' '
  #     object_nl: "\n"
  #     array_nl: "\n"

# Find translate calls
search:
  ## Paths or `File.find` patterns to search in:
  paths:
   - app/
   - lib/

  ## Root directories for relative keys resolution.
  # relative_roots:
  #   - app/controllers
  #   - app/helpers
  #   - app/mailers
  #   - app/presenters
  #   - app/views

  ## Files or `File.fnmatch` patterns to exclude from search. Some files are always excluded regardless of this setting:
  ##   %w(*.jpg *.png *.gif *.svg *.ico *.eot *.otf *.ttf *.woff *.woff2 *.pdf *.css *.sass *.scss *.less *.yml *.json)
  exclude:
    - app/assets/images
    - app/assets/fonts

  ## Alternatively, the only files or `File.fnmatch patterns` to search in `paths`:
  ## If specified, this settings takes priority over `exclude`, but `exclude` still applies.
  # only: ["*.rb", "*.html.slim"]

  ## If `strict` is `false`, guess usages such as t("categories.#{category}.title"). The default is `true`.
  # strict: true

  ## Multiple scanners can be used. Their results are merged.
  ## The options specified above are passed down to each scanner. Per-scanner options can be specified as well.
  ## See this example of a custom scanner: https://github.com/glebm/i18n-tasks/wiki/A-custom-scanner-example

## Google Translate
# translation:
#   # Get an API key and set billing info at https://code.google.com/apis/console to use Google Translate
#   api_key: "AbC-dEf5"

## Do not consider these keys missing (will not be translated):
ignore_missing:
  - 'languages_localized.*'
  - 'privacy_notice'
  - 'privacy_notice.*'
  - 'privacy_policy.*'
  - 'cookies_notice'
  - 'cookies_notice.*'

## Consider these keys used:
ignore_unused:
  - 'privacy_notice.*'
  - 'activerecord.attributes.*'
  - 'activerecord.errors.*'
  - 'dry_errors.*'
  - 'activemodel.errors.*'
  - 'cookies_notice'
  - 'cookies_notice.*'
  - '{devise,kaminari,will_paginate}.*'
  - 'simple_form.{yes,no}'
  - 'simple_form.{placeholders,hints,labels}.*'
  - 'simple_form.{error_notification,required}.:'
  - 'administration.templates.questions.*'
  - 'administration.templates.blocks.*'
  - 'administration.navigation.factors.*'
  - 'administration.navigation.occupations.*'
  - 'administration.campaign_templates.list.*'
  - 'administration.campaigns.assessment_reports.report_approval.*'
  - 'administration.campaigns.assessment_reports.scoring_approval.*'
  - 'administration.dimensions.list.*'
  - 'administration.norms.list.*'
  - 'administration.factors.list.*'
  - 'administration.libraries.list.*'
  - 'administration.communications.list.*'
  - 'administration.table.entries.*'
  - 'administration.profiles.*'
  - 'administration.innovation_styles.list.*'
  - 'administration.innovation_styles_factors.list.*'
  - 'administration.occupations.list.*'
  - 'administration.occupations_factors.list*'
  - 'checking_wizard.steps*'
  - 'assessments.actions.pending_tasks*'
  - 'validations.title.*'
  - 'time.formats.*'
  - 'administration.imports.errors.*'
  - 'administration.assessments.copy.successfully'
  - 'administration.assessments.destroy.successfully'
  - 'administration.assessments.edit.header'
  - 'administration.assessments.new.header'
  - 'administration.assessments.restore.successfully'
  - 'administration.assessments.soft_delete.successfully'
  - 'administration.assessments.toggle_archive.successfully'
  - 'administration.assessments.toggle_status.successfully'
  - 'administration.assigns.destroy.successfully'
  - 'administration.assigns.new.header'
  - 'administration.assigns_reports.edit.header'
  - 'administration.blocks.copy.successfully'
  - 'administration.blocks.destroy.successfully'
  - 'administration.blocks.edit.header'
  - 'administration.blocks.new.header'
  - 'administration.campaign_templates.copy.successfully'
  - 'administration.campaign_templates.edit.header'
  - 'administration.campaign_templates.new.header'
  - 'administration.campaign_templates.toggle_status.successfully'
  - 'administration.clients.copy.successfully'
  - 'administration.clients.edit.header'
  - 'administration.clients.new.header'
  - 'administration.communications.edit.header'
  - 'administration.communications.new.header'
  - 'administration.communications.toggle_status.successfully'
  - 'administration.development_actions.destroy.successfully'
  - 'administration.development_actions.edit.header'
  - 'administration.development_actions.new.header'
  - 'administration.development_actions.toggle_status.successfully'
  - 'administration.dimensions.edit.header'
  - 'administration.dimensions.new.header'
  - 'administration.dimensions.toggle_status.successfully'
  - 'administration.dimensions.translations.header'
  - 'administration.factors.copy.successfully'
  - 'administration.factors.edit.header'
  - 'administration.factors.new.header'
  - 'administration.factors.toggle_status.successfully'
  - 'administration.imports_assessments_result_imports.new.header'
  - 'administration.imports_hris_imports.new.header'
  - 'administration.imports_user_imports.new.header'
  - 'administration.innovation_styles.edit.header'
  - 'administration.innovation_styles.new.header'
  - 'administration.innovation_styles.toggle_status.successfully'
  - 'administration.innovation_styles_factors.edit.header'
  - 'administration.innovation_styles_factors.new.header'
  - 'administration.innovation_styles_factors.toggle_status.successfully'
  - 'administration.libraries.edit.header'
  - 'administration.libraries.new.header'
  - 'administration.memberships.admin_chosen.successfully'
  - 'administration.memberships.destroy.successfully'
  - 'administration.memberships.new.header'
  - 'administration.memberships.reset_password.successfully'
  - 'administration.memberships.toggle_membership_status.successfully'
  - 'administration.memberships.toggle_status.successfully'
  - 'administration.norms.edit.header'
  - 'administration.norms.new.header'
  - 'administration.norms.toggle_status.successfully'
  - 'administration.occupations.edit.header'
  - 'administration.occupations.new.header'
  - 'administration.occupations.toggle_status.successfully'
  - 'administration.occupations_factors.edit.header'
  - 'administration.occupations_factors.new.header'
  - 'administration.occupations_factors.toggle_status.successfully'
  - 'administration.questions.copy.successfully'
  - 'administration.questions.destroy.successfully'
  - 'administration.questions.edit.header'
  - 'administration.questions.new.header'
  - 'administration.questions.toggle_status.successfully'
  - 'administration.report_families.destroy.successfully'
  - 'administration.report_families.edit.header'
  - 'administration.report_families.new.header'
  - 'administration.reports.copy.successfully'
  - 'administration.reports.destroy.successfully'
  - 'administration.reports.edit.header'
  - 'administration.reports.new.header'
  - 'administration.reports.regenerate.successfully'
  - 'administration.reports.restore.successfully'
  - 'administration.reports.soft_delete.successfully'
  - 'administration.reports.toggle_archive.successfully'
  - 'administration.reports.toggle_status.successfully'
  - 'administration.sub_factors.destroy.successfully'
  - 'administration.sub_factors.edit.header'
  - 'administration.sub_factors.new.header'
  - 'administration.sub_factors.toggle_status.successfully'
  - 'administration.users.new.header'
  - 'administration.users.spoof.successfully'
  - 'errors.*'
  - 'administration'
  - 'shared.table.entries.*'
  - idp.history.added_da.*
  - idp.history.removed_da.*
  - idp.history.modified_da.*
  - checking_wizard.video_check.random_phrases.one


## Exclude these keys from the `i18n-tasks eq-base' report:
# ignore_eq_base:
#   all:
#     - common.ok
#   fr,es:
#     - common.brand

## Ignore these keys completely:
# ignore:
#  - kaminari.*

## Sometimes, it isn't possible for i18n-tasks to match the key correctly,
## e.g. in case of a relative key defined in a helper method.
## In these cases you can use the built-in PatternMapper to map patterns to keys, e.g.:
#
# <%#= I18n::Tasks.add_scanner 'I18n::Tasks::Scanners::PatternMapper',
#        only: %w(*.html.haml *.html.slim),
#        patterns: [['= title\b', '.page_title']] %>
#
# The PatternMapper can also match key literals via a special %{key} interpolation, e.g.:
#
# <%#= I18n::Tasks.add_scanner 'I18n::Tasks::Scanners::PatternMapper',
#        patterns: [['\bSpree\.t[( ]\s*%{key}', 'spree.%{key}']] %>

csv:
  export:
    - tmp/i18n-export/export.csv
  import:
    - tmp/i18n-export/import.csv
