# Use sidekiq-cron recommened site https://crontab.guru/
# to generate/verify cronschedule expressions

license_expiry_check_job:
  cron: "30 9 */1 * *" # At 09:30 on every day-of-month
  class: Licenses::ExpiryCheckJob
  queue: cron_tasks

communications_other_type_job:
  cron: "*/5 * * * *" # At every 5th minute
  class: Communications::OtherTypeJob
  queue: communication

new_assignment_communications:
  cron: "*/5 * * * *" # At every 5th minute
  class: Communications::NewAssignmentJob
  queue: communication

workshop_upcoming_reminder_job:
  cron: "0 10 */1 * *" # At 10:00 on every day-of-month
  class: Communications::WorkshopUpcomingReminderJob
  queue_as: cron_tasks

threesixty_send_scheduled_email_job:
  cron: "*/1 * * * *" # At every minute
  class: Threesixty::SendScheduledEmailJob
  queue: cron_tasks

threesixty_send_reminders_job:
  cron: "0 10 */1 * *" # At 10:00 on every day-of-month
  class: Threesixty::SendRemindersJob
  queue_as: cron_tasks

users_results_handle_expire_job:
  cron: "*/5 * * * *" # At every 5th minute
  class: HandleUserResultExpiryJob
  queue_as: cron_tasks

weekly_stats_job:
  cron: "0 10 * * SUN" # At 10:00 on Sunday
  class: Licenses::WeeklyStatsJob
  queue_as: cron_tasks

campaign_status_updater_job:
  cron: "*/1 * * * *" # Every 1 minutes
  class: CampaignStatusUpdaterJob
  queue_as: cron_tasks

campaign_user_status_updater_job:
  cron: "*/1 * * * * " # Every minute
  class: TimeoutCampaignUserJob
  queue_as: cron_tasks

cleaner_admin_job:
  cron: "0 5 * * SUN" # At 5:00 on Sunday
  class: CleanerAdminJob
  queue_as: cron_tasks

cleaner_bulk_report_job:
  cron: "0 5 * * SUN" # At 5:00 on Sunday
  class: BulkReportCleanerJob
  queue_as: cron_tasks

remove_soft_deleted_resources:
  cron: "0 6 * * SUN" # At 6:00 on Sunday
  class: RemoveSoftDeletedResources
  queue_as: cron_tasks

# fetch_iiht_assessments:
#   cron: "0 6 */1 * *" # At 06:00 on every day-of-month
#   class: Iiht::FetchAssessmentsJob
#   queue_as: cron_tasks

load_pearson_assessments_to_table:
  cron: "0 6 */1 * *" # At 06:00 on every day-of-month
  class: Pearson::LoadAssessmentsToTableJob
  queue_as: cron_tasks

recalculate_proctoring_credits:
  cron: "*/10 * * * *" # Every 10 minutes
  class: Licenses::RecalculateProctoringCredits
  queue_as: cron_tasks

export_auditlogs:
  cron: "*/15 * * * *" # Every 15 minutes
  class: ClientAuditlogExportSettings::ExportAllAuditLogsJob
  queue_as: cron_tasks

refresh_audit_log_cache:
  cron: "0 1 * * *"  # Every day at 01:00 AM
  class: RefreshAuditLogCacheJob
  queue_as: cron_tasks

send_assessor_notifications:
  cron: "*/30 * * * *"  # Every 30 minutes
  class: SendAssessorNotificationsJob
  queue_as: cron_tasks

scheduled_digest_emails:
  cron: "*/10 * * * *"  # Every 10 minutes
  class: ScheduledDigestEmailsJob
  queue_as: cron_tasks

idp_deadline_notification_job:
  cron: "0 9 */1 * *" # Run at 9:00 AM every day
  class: Idp::DeadlineNotificationJob
  queue_as: cron_tasks

disable_inactive_users:
  cron: "0 5 * * *"  # Runs daily at 5 AM
  class: DisableInactiveUsersJob
  queue: cron_tasks

send_idp_comments_notifications:
  cron: "0 */12 * * *" # At every 12th hour
  class: SendIdpCommentsNotificationsJob
  queue_as: cron_tasks

disable_unreachable_webhook_job:
  cron: "0 2 * * *" # Runs daily at 2 AM
  class: DisableUnreachableWebhooksJob
  queue: cron_tasks

delete_expired_meeting_recordings_job:
  cron: "0 3 * * *" # Runs daily at 3 AM
  class: MeetingRecordings::DeleteExpiredRecordingsJob
  queue_as: cron_tasks

yoodli_daily_import:
  cron: "0 4 * * *" # Runs daily at 4 AM
  class: YoodliDailyImportJob
  queue_as: cron_tasks

session_cleanup:
  cron: "0 3 * * *" # Runs daily at 3 AM
  class: SessionCleanupJob
  queue_as: cron_tasks

data_report_job_cleanup_job:
  cron: "0 1 * * *" # Runs daily at 01:00 AM
  class: DataReports::DataReportJobCleanupJob
  queue_as: cron_tasks
