# Use sidekiq-cron recommened site https://crontab.guru/
# to generate/verify cronschedule expressions

license_expiry_check_job:
  cron: "30 9 */1 * *" # At 09:30 on every day-of-month
  class: Licenses::ExpiryCheckJob
  queue: cron_tasks

communications_other_type_job:
  cron: "*/5 * * * *" # At every 5th minute
  class: Communications::OtherTypeJob
  queue: communication

threesixty_send_scheduled_email_job:
  cron: "*/1 * * * *" # At every minute
  class: Threesixty::SendScheduledEmailJob
  queue: cron_tasks

threesixty_send_reminders_job:
  cron: "0 10 */1 * *" # At 10:00 on every day-of-month
  class: Threesixty::SendRemindersJob
  queue_as: cron_tasks

users_results_handle_expire_job:
  cron: "*/10 * * * *" # At every 10th minute
  class: HandleUserResultExpiryJob
  queue_as: cron_tasks

weekly_stats_job:
  cron: "0 6 * * SUN UTC" # At 06:00 on Sunday
  class: Licenses::WeeklyStatsJob
  queue_as: cron_tasks
