\default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  encrypted_key: <%= ENV["ENCRYPTED_KEY"] %>
  rack_timeout:
    service_timeout: 600
    wait_timeout: false
    wait_overtime: false
    service_past_wait: false
  secret_token_for_generate: <%= ENV["SECRET_TOKEN_FOR_GENERATE"] %>
  hogan:
    client_id: <%= ENV["HOGAN_CLIENT_ID"] %>
    client_user_id: <%= ENV["HOGAN_CLIENT_USER_ID"] %>
    client_password: <%= ENV["HOGAN_CLIENT_PASSWORD"] %>
    login_url: <%= ENV["HOGAN_LOGIN_URL"] %>
    wsdl_url: <%= ENV["HOGAN_WSDL_URL"] %>
    # SecureRandom.base64(32)
    encrypted_key: <%= ENV["HOGAN_ENCRYPTED_KEY"] %>
  http_auth: <%= ENV["HTTP_AUTH_CREDENTIALS"] %>
  # S3
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  region: <%= ENV["AWS_REGION"] %>
  directory: <%= ENV["AWS_S3_BUCKET"] %>
  chrome_path: google-chrome

development:
  <<: *default
  secret_key_base: '010fe4db92e5c637465026aac8e35148fe08c7965f11ef3267d9a387b6f4105464de2f615e3e1ee1c5c53134182d8b62d87460ba58e0436424a926f5ae1fd101'

# Do not keep production secrets in the repository,
# instead read values from the environment.

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default

staging:
  <<: *default

test:
  secret_token_for_generate: '58a3ad71ef7159932680920ea21f8c5f882dee98cd7893578aeb7c786ac651486a976e352df06d562bde00ac21d21c778b4f4d4a41633c607b08426d584b4d4a'
  secret_key_base: '010fe4db92e5c637465026aac8e35148fe08c7965f11ef3267d9a387b6f4105464de2f615e3e1ee1c5c53134182d8b62d87460ba58e0436424a926f5ae1fd101'
  encrypted_key: nu24x9RAy6tKuOW6rFvEPsB7hehnAI5ixicyqKqgcU4=
  rack_timeout:
    service_timeout: false
    wait_timeout: false
    wait_overtime: false
    service_past_wait: false
  hogan:
    client_id: 123
    client_user_id: 123
    client_password: 123
    login_url: 123
    wsdl_url: 123
    # SecureRandom.base64(32)
    encrypted_key: nu24x9RAy6tKuOW6rFvEPsB7hehnAI5ixicyqKqgcU4=
  http_auth: user:password
