project_name: Psychometrics
timezone: Abu Dhabi
timezone_tip: ' (GST)'
react_dev:
  reports: false
  assessments: false
hashids_length:
  anonym: 8
  assign_id: 6
languages:
  - es
  - fr
  - cn
  - ar
  - de
currencies:
  - USD
  - EUR
  - GBP
  - AED
  - INR
  - SAR
  - KWD
  - BHD
  - OMR
  - QAR
default_currency: 'USD'
hogan:
  - name: HPI
    assessment_id: HPI
    form_id: 3
    reports:
      - report_id: EcHPIDML
        report_name: HPI Data Report
        norm_id: General
        language_id: en
    factors:
      - id: '01'
        name: Validity
        type: Raw
      - id: '02'
        name: Adjustment
        type: Raw
      - id: '03'
        name: Ambition
        type: Raw
      - id: '04'
        name: Sociability
        type: Raw
      - id: '01'
        name: Validity
        type: Percentile
      - id: '02'
        name: Adjustment
        type: Percentile
      - id: '03'
        name: Ambition
        type: Percentile
      - id: '04'
        name: Sociability
        type: Percentile
  - name: HDS
    assessment_id: HDS
    form_id: 5
    reports:
      - report_id: EcHDSDML
        report_name: HDS Data Report
        norm_id: General
        language_id: en
  - name: MVPI
    assessment_id: MVPI
    form_id: 1
    reports:
      - report_id: EcMVPIDML
        report_name: MVPI Data Report
        norm_id: General
        language_id: en
  - name: HBRI
    assessment_id: HBRIV1
    form_id: 1
    reports:
      - report_id: EcHBRIV1D
        report_name: HBRI Data Report
        norm_id: General
        language_id: en
      - report_id: EcHBRIV1IML
        report_name: HBRI Interpret Report
        norm_id: General
        language_id: en

mindmill:
  - name: Cognitive – Entry Level TTE
    id: 416
  - name: Cognitive – Mid Level TTE
    id: 417
    factors:
      - id: nf.attempted
        type: Count
      - id: nf.correct
        type: Count
      - id: nf.pc
        type: Count
      - id: ed.attempted
        type: Count
      - id: ed.correct
        type: Count
      - id: ed.pc
        type: Count
      - id: nf.zscore
        type: Score
      - id: ed.zscore
        type: Score
      - id: nf.stable
        type: Stability
      - id: ed.stable
        type: Stability
  - name: Cognitive – Senior Level TTE
    id: 418
  - name: Support Functions – Entry Level TTE
    id: 419
  - name: Support Functions – Mid Level TTE
    id: 420
  - name: Support Functions – Senior Level TTE
    id: 421
  - name: Sales – Entry Level TTE
    id: 422
  - name: Sales – Mid Level TTE
    id: 423
  - name: Sales – Senior Level TTE
    id: 424
  - name: Customer – Entry Level TTE
    id: 425
  - name: Customer – Mid Level TTE
    id: 426
  - name: Customer – Senior Level TTE
    id: 427
  - name: Technical Functions – Entry Level TTE
    id: 428
    factors:
      - id: nf.attempted
        type: Count
      - id: nf.correct
        type: Count
      - id: nf.pc
        type: Count
      - id: ed.attempted
        type: Count
      - id: ed.correct
        type: Count
      - id: ed.pc
        type: Count
      - id: nf.zscore
        type: Score
      - id: ed.zscore
        type: Score
      - id: nf.stable
        type: Stability
      - id: ed.stable
        type: Stability
  - name: Technical Functions – Mid Level TTE
    id: 429
  - name: Technical Functions – Senior Level TTE
    id: 430
  - name: Technical Functions
    id: 469
default_colors:
  - "#845EC2"
  - "#2C73D2"
  - "#0089BA"
  - "#008E9B"
  - "#008F7A"
  - "#4B4453"
  - "#C34A36"
  - "#467EBF"
  - "#0098EE"
  - "#D45DB1"
