---
:concurrency: 5
:max_retries: 16
# :pidfile: ./tmp/pids/sidekiq.pid
staging:
  :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 2 %>
production:
  :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 2 %>
:queues:
  - ["two_factor_codes", 10]
  - ["async_request_handler", 9]
  - ["external_results", 6]
  - ["mailers", 6]
  - ["webhooks", 5]
  - ["communication", 4]
  - ["mailers_low_priority", 3]
  - ["reports", 3]
  - ["cron_tasks", 3]
  - ["default", 2]
  - ["low_priority", 1]
