---
:concurrency: 5
# :pidfile: ./tmp/pids/sidekiq.pid
staging:
  :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 2 %>
production:
  :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 2 %>
:queues:
  - two_factor_codes
  - mailers
  - communication
  - reports
  - default
