# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
# amazon:
#   service: S3
#   access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
#   secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
#   region: us-east-1
#   bucket: your_own_bucket

# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket

# Use rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
#   container: your_container_name

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]

test:
  service: Disk
  root: <%= Rails.root.join('tmp/storage') %>

local:
  service: Disk
  root: <%= Rails.root.join('storage') %>

s3_public_bucket:
  service: S3
  access_key_id: <%= Settings.secrets.s3_compatible_storage[:access_key_id] %>
  secret_access_key: <%= Settings.secrets.s3_compatible_storage[:secret_access_key] %>
  region: <%= Settings.secrets.s3_compatible_storage[:region] %>
  bucket: <%= Settings.secrets.s3_compatible_storage[:public_bucket] %>
  public: <%= true %>
  upload:
    cache_control: <%= "public, max-age=#{365.days.to_i}" %>

s3_private_bucket:
  service: S3
  access_key_id: <%= Settings.secrets.s3_compatible_storage[:access_key_id] %>
  secret_access_key: <%= Settings.secrets.s3_compatible_storage[:secret_access_key] %>
  region: <%= Settings.secrets.s3_compatible_storage[:region] %>
  bucket: <%= Settings.secrets.s3_compatible_storage[:private_bucket] %>
  public: <%= false %>
  upload:
    cache_control: <%= "public, max-age=#{365.days.to_i}" %>

s3_dailyco_bucket:
  service: S3
  access_key_id: <%= Settings.secrets.s3_compatible_storage[:access_key_id] %>
  secret_access_key: <%= Settings.secrets.s3_compatible_storage[:secret_access_key] %>
  region: <%= Settings.secrets.s3_compatible_storage[:region] %>
  bucket: <%= Settings.secrets.s3_compatible_storage[:dailyco_bucket] %>
  public: <%= false %>
  upload:
    cache_control: <%= "public, max-age=#{365.days.to_i}" %>

cloudfront_public_bucket:
  service: CloudfrontAdapter
  access_key_id: <%= Settings.secrets.s3_compatible_storage[:access_key_id] %>
  secret_access_key: <%= Settings.secrets.s3_compatible_storage[:secret_access_key] %>
  region: <%= Settings.secrets.s3_compatible_storage[:region] %>
  bucket: <%= Settings.secrets.s3_compatible_storage[:public_bucket] %>
  cloudfront_domain: <%= Settings.cloudfront_domain %>
  cloudfront_key_pair_id: <%= ENV['CLOUDFRONT_KEY_PAIR_ID'] %>
  cloudfront_private_key: |
    <%= ENV.fetch('CLOUDFRONT_PRIVATE_KEY', '').gsub("\n", "\n    ") %>
  cloudfront_expires_in: <%= ENV.fetch('CLOUDFRONT_SIGNED_URL_EXPIRES_IN', 600).to_i %>
  public: <%= true %>
  upload:
    cache_control: <%= "public, max-age=#{365.days.to_i}" %>

cloudfront_private_bucket:
  service: CloudfrontAdapter
  access_key_id: <%= Settings.secrets.s3_compatible_storage[:access_key_id] %>
  secret_access_key: <%= Settings.secrets.s3_compatible_storage[:secret_access_key] %>
  region: <%= Settings.secrets.s3_compatible_storage[:region] %>
  bucket: <%= Settings.secrets.s3_compatible_storage[:private_bucket] %>
  cloudfront_domain: <%= Settings.cloudfront_domain %>
  cloudfront_key_pair_id: <%= ENV['CLOUDFRONT_KEY_PAIR_ID'] %>
  cloudfront_private_key: |
    <%= ENV.fetch('CLOUDFRONT_PRIVATE_KEY', '').gsub("\n", "\n    ") %>
  cloudfront_expires_in: <%= ENV.fetch('CLOUDFRONT_SIGNED_URL_EXPIRES_IN', 600).to_i %>
  public: <%= false %>
  upload:
    cache_control: <%= "public, max-age=#{365.days.to_i}" %>

cloudfront_dailyco_bucket:
  service: CloudfrontAdapter
  access_key_id: <%= Settings.secrets.s3_compatible_storage[:access_key_id] %>
  secret_access_key: <%= Settings.secrets.s3_compatible_storage[:secret_access_key] %>
  region: <%= Settings.secrets.s3_compatible_storage[:region] %>
  bucket: <%= Settings.secrets.s3_compatible_storage[:dailyco_bucket] %>
  cloudfront_domain: <%= Settings.cloudfront_domain %>
  cloudfront_key_pair_id: <%= ENV['CLOUDFRONT_KEY_PAIR_ID'] %>
  cloudfront_private_key: |
    <%= ENV.fetch('CLOUDFRONT_PRIVATE_KEY', '').gsub("\n", "\n    ") %>
  cloudfront_expires_in: <%= ENV.fetch('CLOUDFRONT_SIGNED_URL_EXPIRES_IN', 600).to_i %>
  public: <%= false %>
  upload:
    cache_control: <%= "public, max-age=#{365.days.to_i}" %>
