
export const INIT = 'flow_processor/INIT'
export const NEXT_PAGE = 'flow_processor/NEXT_PAGE'
export const PREV_PAGE = 'flow_processor/PREV_PAGE'
export const ADD_PREV_PAGE = 'flow_processor/ADD_PREV_PAGE'
export const REMOVE_PREV_PAGE = 'flow_processor/REMOVE_PREV_PAGE'
export const ANSWER = 'flow_processor/ANSWER'
export const SHOW_PAGE = 'flow_processor/SHOW_PAGE'
export const SHOW_END = 'flow_processor/SHOW_END'
export const CHANGE_ELEMENT = 'flow_processor/CHANGE_ELEMENT'
export const SHOW_ERRORS = 'flow_processor/SHOW_ERRORS'
export const EMPTY_ERRORS = 'flow_processor/EMPTY_ERRORS'
export const SAVE_RESULTS = 'flow_processor/SAVE_RESULTS'
export const SET_EMBEDDED_DATA = 'flow_processor/SET_EMBEDDED_DATA'
export const HIDE_QUESTION = 'flow_processor/HIDE_QUESTION'
export const SHOW_QUESTION = 'flow_processor/SHOW_QUESTION'
export const SET_DIRTY_RESULTS = 'flow_processor/SET_DIRTY_RESULTS'
export const SET_NOT_DIRTY_RESULTS = 'flow_processor/SET_NOT_DIRTY_RESULTS'

export const TOGGLE_HIDDEN_QUESTIONS = 'preview/TOGGLE_HIDDEN_QUESTIONS'
export const TOGGLE_IGNORE_VALIDATION = 'preview/TOGGLE_IGNORE_VALIDATION'
export const RESET = 'preview/RESET'
export const UPDATE_HIGHLIGHT = 'flow_processor/UPDATE_HIGHLIGHT'
export const UPDATE_HIGHLIGHT_REQUEST = 'flow_processor/UPDATE_HIGHLIGHT_REQUEST'
export const SET_LOCAL_RESULTS = 'flow_processor/SET_LOCAL_RESULTS'

export const MARK_QUESTION_IN_PROGRESS = 'flow_processor/MARK_QUESTION_IN_PROGRESS'
export const REMOVE_QUESTION_IN_PROGRESS = 'flow_processor/REMOVE_QUESTION_IN_PROGRESS'
export const CLEAR_IN_PROGRESS_QUESTION = 'flow_processor/CLEAR_IN_PROGRESS_QUESTION'
