export default {
  Text: {},

  Image: {},

  Shape: {},

  Graph: {
    charts: {
      Bar: 'Bar',
      Bar3D: '3D Bar',
      HorizontalBar: 'Horizontal Bar',
      HorizontalBar3D: '3D Horizontal Bar',
      StackedBar: 'Stacked Bar',
      StackedBar3D: '3D Stacked Bar',
      StackedHorizontalBar: 'Stacked Horizontal Bar',
      StackedHorizontalBar3D: '3D Stacked Horizontal Bar',
      Area: 'Area',
      Area3D: '3D Area',
      StackedPercentArea: 'Stacked Area Percent',
      StackedPercentArea3D: '3D Stacked Percent Area',

      Pie: 'Pie',
      Pie3D: '3D Pie',
      Radar: 'Radar',
      AreaRadar: 'Area Radar',
      StackedPercentBar: 'Stacked Percent Bar',
      StackedPercentBar3D: '3D Stacked Percent Bar',
      StackedPercentHorizontalBar: 'Stacked Percent Horizontal Bar',
      StackedPercentHorizontalBar3D: '3D Stacked Percent Horizontal Bar',
      StackedArea: 'Stacked Area',
      StackedArea3D: '3D Stacked Area',
      CompositeBar: 'Composite Bar',
      PerceptionMap: 'Perception Map',

      Line: 'Line',
      PlotedLine: 'Ploted Line',
      Spline: 'Spline',
      PlotedSpline: 'Ploted Spline',
      Plot: 'Plot',
      RegressionPlot: 'Regression Plot',
      Gauge: 'Gauge',
      MultiGauge: 'Multi Gauge',
      HalfGauge: 'Half Gauge',
      HalfMultiGauge: 'Half Multi Gauge',
      CompositeRadar: 'Composite Radar',
      TagCloud: 'Tag Cloud',
      CustomPie: 'Custom Pie',
      Engagometer: 'Engagometer',
      Circumplex: 'Circumplex',
      Consultant: 'Consultant',
    },
    chartsIcons: {
      Bar: 'Bar',
      Bar3D: 'Bar3D',
      HorizontalBar: 'HorizontalBar',
      HorizontalBar3D: 'HorizontalBar3D',
      StackedBar: 'StackedBar',
      StackedBar3D: 'StackedBar3D',
      StackedHorizontalBar: 'StackedHorizontalBar',
      StackedHorizontalBar3D: 'StackedHorizontalBar3D',
      Area: 'Area',
      Area3D: 'Area3D',
      StackedPercentArea: 'StackedPercentArea',
      StackedPercentArea3D: 'StackedPercentArea3D',

      Pie: 'Pie',
      Pie3D: 'Pie3D',
      Radar: 'Radar',
      AreaRadar: 'AreaRadar',
      StackedPercentBar: 'StackedPercentBar',
      StackedPercentBar3D: 'StackedPercentBar3D',
      StackedPercentHorizontalBar: 'StackedPercentHorizontalBar',
      StackedPercentHorizontalBar3D: 'StackedPercentHorizontalBar3D',
      StackedArea: 'StackedArea',
      StackedArea3D: 'StackedArea3D',
      CompositeBar: 'CompositeBar',
      PerceptionMap: 'PerceptionMap',

      Line: 'Line',
      PlotedLine: 'PlotedLine',
      Spline: 'Spline',
      PlotedSpline: 'PlotedSpline',
      Plot: 'Plot',
      RegressionPlot: 'RegressionPlot',
      Gauge: 'Gauge',
      CustomPie: 'CustomPie',
      Circumplex: 'Circumplex',
      Consultant: 'Consultant',
      Engagometer: 'Engagometer',
      MultiGauge: 'MultiGauge',
      HalfGauge: 'HalfGauge',
      HalfMultiGauge: 'HalfMultiGauge',
      CompositeRadar: 'CompositeRadar',
      TagCloud: 'TagCloud',
    },
    filtersDataSet: {
      TagCloud: {
        Question: ['TextEntry'],
        EmbeddedData: false,
        Factor: false,
      },
      Gauge: {
        Question: false,
        EmbeddedData: false,
        Factor: true,
      },
      Radar: {
        Question: false,
        EmbeddedData: false,
        Factor: true,
      },
      CustomPie: {
        Question: false,
        EmbeddedData: false,
        Factor: true,
      },
      Circumplex: {
        Question: false,
        EmbeddedData: false,
        // possible values: factor, subfactor, true
        Factor: 'factor',
      },
      Consultant: {
        Question: false,
        EmbeddedData: false,
        // possible values: factor, subfactor, true
        Factor: true,
      },
      StackedBar: {
        Question: false,
        EmbeddedData: false,
        Factor: true,
      },
      Engagometer: {
        Question: false,
        EmbeddedData: false,
        Factor: true,
      },
    },
    // add access to multiFiltering (by default: false)
    settings: {
      Bar: {
        multiFiltering: true,
      },
      Radar: {
        multiFiltering: true,
      },
      CustomPie: {
        multiFiltering: true,
      },
    },
  },

  Table: {
    labels: {
      SingleQuestion: 'Single Question',
      Statistic: 'Statistic',
      SimpleTable: 'Simple Table',
      ThreeSixtyDefault: 'Default 360',
      HighestLowest: 'Highest/Lowest',
      GapAssessment: 'Gap Assessment',
      ThreeSixtyReportSummary: '360 Report Summary',
      SingleValue: 'Single Value',
      Competencies: 'Competencies',
      HrisData: 'HRIS Data Table',
      VideoResponse: 'Video Response',
      ResponseSummary: 'Response Summary Statistics',
      FactorQuestionsScore: 'Factor - Questions Mean Score',
      HighestLowestScore: 'Highest - Lowest Mean Score',
      HighestLowestQuestion: 'Highest - Lowest Questions Score',
      HighestLowestSubject: 'Highest-Lowest Subject score',
      SingleValueScoring: 'Single Value - Scoring',
      GapAssessmentScoring: 'Gap Assessment - Scoring',
      AgileFactors: 'Agile Factors',
      CPITopFactors: 'Career - Top Factors',
      CPIOccupations: 'Career - Occupations',
      PotentialCareerShort: 'Career - Potential (short)',
      PotentialCareerFull: 'Career - Potential (full)',
      StrengthClusters: 'Career - Strength Clusters',
      PotentialKeyCareerTracks: 'Career - Key Tracks',
      InnovationStyles: 'Innovation Styles',
    },

    filtersDataSet: {
      FactorQuestionsScore: {
        Question: false,
        EmbeddedData: false,
        Factor: true,
      },
      SingleValueScoring: {
        Question: false,
        EmbeddedData: false,
        Factor: true,
      },
      AgileFactors: {
        Question: ['PickGroupRank'],
      },
      HighestLowest: {
        Question: true,
        EmbeddedData: false,
        Factor: true,
      },
    },

    settings: {
      HighestLowestSubject: { multiFiltering: true },
      SingleValueScoring: { multiFiltering: true },
      GapAssessment: { multiFiltering: true },
      ThreeSixtyDefault: { multiFiltering: true },
      FactorQuestionsScore: { multiFiltering: true },
      GapAssessmentScoring: { multiFiltering: true },
      AgileFactors: { questionMultiFiltering: true },
      ThreeSixtyReportSummary: { multiFiltering: true },
      VideoResponse: { multiFiltering: true },
      SingleValue: { multiFiltering: true },
      Competencies: { multiFiltering: true },
    },

    HrisData: {
      defaultLabels: ['Division', 'Respondent Count', 'Invitee count', 'Percentage'],
    },
    defaultProps: {
      HighestLowest: {
        sourceType: 'Question',
      },
      ThreeSixtyDefault: {
        sourceType: 'Factor',
        factorId: '',
        questionId: '',
      },
      GapAssessment: {
        sourceType: 'Factor',
      },
      SingleValue: {
        sourceType: 'Factor',
        factorIds: [],
        questionChoiceIds: [],
        filter: [],
      },
      Competencies: {
        sourceType: 'Factor',
        factorIds: [],
        questionChoiceIds: [],
        filter: [],
        mainHeaderColor: '#064655',
        secondHeaderColor: '#22A6C0',
        showLabels: true,
        showValues: true,
        showLines: true,
        colors: [
          { id: 1, color: '#4572A7' },
          { id: 2, color: '#AA4643' },
          { id: 3, color: '#89A54E' },
          { id: 4, color: '#71588F' },
          { id: 5, color: '#4198AF' },
          { id: 6, color: '#DB843D' },
          { id: 7, color: '#93A9CF' },
          { id: 8, color: '#D19392' },
          { id: 9, color: '#B9CD96' },
          { id: 10, color: '#A99BBD' },
        ],
        milestones: [{
          id: 1, min: 1.0, max: 2.0, name: 'Range 1',
        }, {
          id: 2, min: 2.0, max: 3.0, name: 'Range 2',
        }],
      },
      VideoResponse: {
        filter: [],
      },
    },
  },
}
