# frozen_string_literal: true

class AddTenantIdColumns < ActiveRecord::Migration[8.0] # rubocop:disable Metrics/ClassLength
  TABLES = %i[
    active_storage_attachments
    admin_jobs
    admin_roles
    agiles
    ai_assistant_output_schema_keys
    ai_assistant_requests
    ai_assistant_tool_calls
    ai_assistant_chats
    ai_assisted_user_sessions
    ai_assistants
    ai_factor_scores
    ai_scoring_approval_settings
    ai_translation_results
    assessment_assistants
    assessment_consent_settings
    assessments
    assessments_reports
    assessors
    audit_logs
    blocks
    bulk_reports
    campaign_ai_artifact_dependencies
    campaign_ai_artifacts
    campaign_assessment_groups
    campaign_assessments
    campaign_assessor_assessment_factor_weights
    campaign_assessor_assessments
    campaign_factor_groups
    campaign_factor_values
    campaign_factors
    campaign_idp_dependencies
    campaign_idps
    campaign_options
    campaign_reports
    campaign_users
    campaigns
    campaign_templates
    client_ai_assistants
    client_auditlog_export_settings
    client_features
    client_privacy_settings
    clients
    communication_cc_users
    communication_email_resources
    communication_emails
    communications
    communications_assessments
    communications_copy_memberships
    communications_memberships
    communications_users
    dashboards
    data_report_jobs
    data_reports
    datasheet_column_preferences
    design_settings
    development_actions
    dimensions
    factor_benchmark_scores
    factors
    factors_aliases
    factors_norms
    factors_scoring
    factors_sub_factors
    highlights
    hogan_credentials
    hogan_logs
    hogan_report_settings
    idp_report_pdfs
    idp_settings
    idp_template_development_actions
    idp_template_interview_questions
    idp_template_reflection_questions
    idp_template_skills
    idp_templates
    iiht_user_assessments
    innovation_styles
    innovation_styles_factors
    integrations
    interview_questions
    job_groups
    job_roles
    libraries
    license_usages
    licenses
    media_responses
    meeting_recordings
    meeting_rooms
    membership_grants
    memberships
    memberships_admin_roles
    mettl_assessments
    mettl_schedule_records
    mettl_user_assessments
    mhs_user_assessments
    norms
    notifications
    occupations
    occupations_factors
    pearson_user_assessments
    power_bi_settings
    privacy_consents
    privacy_settings
    proctoring_sessions
    proficiency_levels
    profile_fields
    profile_field_values
    profile_settings
    project_assessments
    project_features
    project_licenses
    question_recoding
    questions
    reflection_questions
    registration_codes
    registration_settings
    relationships
    report_approval_settings
    reports
    reports_campaign_ai_artifacts
    reports_campaign_factors
    reports_filters
    reports_modules
    reports_pages
    resource_hogan_credentials
    saml_service_providers
    saml_settings
    saville_factors
    saville_report_settings
    saville_user_assessments
    security_settings
    sheet_columns
    sheet_row_data
    sheet_rows
    sheets
    simulation_user_assessments
    skill_aliases
    skill_groups
    skills
    skills_development_actions
    skills_job_roles
    skillvue_assessments
    skillvue_user_assessments
    sms_histories
    sms_invites
    sms_records
    smtp_settings
    taxonomy_levels
    text_module_overrides
    threesixty_campaigns
    threesixty_email_histories
    threesixty_email_schedules
    threesixty_email_templates
    threesixty_evaluators
    threesixty_instruction_templates
    threesixty_nomination_requirements
    threesixty_options
    threesixty_reminder_histories
    threesixty_subjects
    transcriptions
    user_assessment_factor_scores
    user_assessment_verification_images
    user_assessment_verification_media
    user_assessments
    user_bookings
    user_idp_comments
    user_idp_development_actions
    user_idp_plans
    user_idp_skills
    user_reflection_question_answers
    user_report_comments
    user_report_events
    user_report_pdfs
    user_reports
    user_profiles
    users
    users_results
    vector_embeddings
    webhook_event_logs
    webhook_subscription_topics
    webhook_subscriptions
    workshop_assessors
    workshop_invite_logs
    workshop_invited_subjects
    workshop_invites
    workshop_managers
    workshop_resources
    workshop_subjects
    workshops
    yoodli_user_assessments
    system_check_sessions
    system_check_records
    taggings
    version_associations
    versions
  ].freeze

  # rubocop:disable CustomRubocops/AvoidActiveRecordInMigrations
  def up
    TABLES.each do |table|
      add_column table, :tenant_id, :bigint unless column_exists?(table, :tenant_id)
    end
  end

  def down
    TABLES.each do |table|
      remove_column table, :tenant_id if column_exists?(table, :tenant_id)
    end
  end
  # rubocop:enable CustomRubocops/AvoidActiveRecordInMigrations
end
