apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ template "lighthouse.fullname" . }}-external-secret
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
spec:
  refreshInterval: 2m
  secretStoreRef:
    kind: SecretStore
    name: {{ template "lighthouse.fullname" . }}-secret-store
  target:
    name: {{ template "lighthouse.fullname" . }}-eso-secrets
    creationPolicy: Owner
  dataFrom:
  - find:
      name:
        regexp: ".*"
