{{- if .Values.objectStorageProxy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "oci-ic-lhksa"
    nginx.ingress.kubernetes.io/proxy-body-size: 400m
    nginx.ingress.kubernetes.io/backend-protocol: https
    nginx.ingress.kubernetes.io/upstream-vhost: "{{ .Values.objectStorageProxy.vHost }}"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "*"
    nginx.ingress.kubernetes.io/cors-expose-headers: "etag"
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_ssl_name {{ .Values.objectStorageProxy.vHost }};
      proxy_ssl_server_name on;
  name: {{ template "lighthouse.fullname" . }}-obj-st-rp-ingress
  labels:
    app: {{ template "lighthouse.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  {{- if .Values.objectStorageProxy.ingress.tls }}
  tls:
    {{- range .Values.objectStorageProxy.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.objectStorageProxy.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .backend.service.name }}
                port:
                  number: {{ int .backend.service.port.number }}
          {{- end }}
    {{- end }}
{{- end -}}
