apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ template "lighthouse.fullname" . }}-secret-store
spec:
  provider:
    oracle:
      vault: {{ .Values.oracle.vaultOcid }}
      region: {{ .Values.oracle.region }}
      compartment: {{ .Values.oracle.compartmentOcid }}
      encryptionKey: {{ .Values.oracle.masterEncryptionKeyOcid }}
      principalType: InstancePrincipal
