apiVersion: v1
kind: Secret
metadata:
  name: {{ template "lighthouse.fullname" . }}-secrets
  labels:
    app: {{ template "lighthouse.fullname" . }}
type: Opaque
data:
{{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
