apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "lighthouse.fullname" . }}-web
  creationTimestamp: null
  labels:
    app: {{ template "lighthouse.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ int .Values.web.replica }}
  selector:
    matchLabels:
      app: {{ template "lighthouse.fullname" . }}
      release: "{{ .Release.Name }}"
      role: web
  minReadySeconds: 10
  {{- with .Values.webDeploymentStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
    {{- end }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ template "lighthouse.fullname" . }}
        release: "{{ .Release.Name }}"
        imageTag: "{{ .Values.image.tag }}"
        role: web
        pdb: include
      annotations:
        rollme: {{ template "rollme" . }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - args:
            - exec
            - falcon
            - host
          command:
            - bundle
          env:
            - name: PORT
              value: {{ .Values.services.internlPort | quote }}
          envFrom:
            - configMapRef:
                name: {{ template "lighthouse.fullname" . }}-env
            - secretRef:
                name: {{ template "lighthouse.fullname" . }}-eso-secrets
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: {{ .Chart.Name }}-web
          ports:
            - containerPort: {{ int .Values.services.internlPort }}
          livenessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /
              port: {{ int .Values.services.internlPort }}
              httpHeaders:
              - name: Host
                value: "{{ .Values.env.APP_SUB_DOMAIN }}.{{ .Values.env.APP_DOMAIN }}"
          readinessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /
              port: {{ int .Values.services.internlPort }}
              httpHeaders:
              - name: Host
                value: "{{ .Values.env.APP_SUB_DOMAIN }}.{{ .Values.env.APP_DOMAIN }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
          {{- with .Values.resources.web }}
          resources:
            {{- toYaml . | nindent 12 }}
            {{- end }}
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: {{ template "lighthouse.fullname" . }}
              release: "{{ .Release.Name }}"
              imageTag: "{{ .Values.image.tag }}"
              role: web
          matchLabelKeys:
            - pod-template-hash

status: {}
