domain: tte-lighthouse.com
subdomain:
port: 443
protocol: 'https'
assigns:
  mindmill_prefix: TTEPROD
hogan:
  - name: HPI
    assessment_id: HPI
    form_id: 3
    reports:
      - report_id: EcHPIDML
        report_name: HPI Data Report
        norm_id: Global
        language_id: en
  - name: HDS
    assessment_id: HDS
    form_id: 5
    reports:
      - report_id: EcHDSDML
        report_name: HDS Data Report
        norm_id: Global
        language_id: en
  - name: MVPI
    assessment_id: MVPI
    form_id: 1
    reports:
      - report_id: EcMVPIDML
        report_name: MVPI Data Report
        norm_id: Global
        language_id: en
  - name: HBRI
    assessment_id: HBRIV1
    form_id: 1
    reports:
      - report_id: EcHBRIV1D
        report_name: HBRI Data Report
        norm_id: Global
        language_id: en
      - report_id: EcHBRIV1IML
        report_name: HBRI Interpret Report
        norm_id: Global
        language_id: en
