domain: <%= ENV["APP_DOMAIN"] || 'tte-lighthouse.com' %> # psychometrics.co.uk
subdomain: <%= ENV["APP_SUB_DOMAIN"] %> # subdomain
port: 
protocol: <%= ENV["APP_PROTOCOL"] || 'http' %>
asset_host: <%= ENV["ASSET_HOST"] %>
file_host: <%= ENV["FILE_HOST"] %>
assigns:
  mindmill_prefix: <%= ENV["MINDMILL_PREFIX"] || 'TTESTAG' %> # set 'TTEPROD' in production environment variables
features:
  two_factor_enabled: <%= ENV['TWO_FACTOR_AUTHENTICATION_ENABLED'] %>
bulk_reports:
  size_limit: <%= ENV.fetch('BULK_REPORTS_ZIP_FILE_SIZE_LIMIT', 200_000_000).to_i %>
