domain: <%= ENV["APP_DOMAIN"] || 'staging.tte-lighthouse.com' %> # psychometrics.co.uk
subdomain: <%= ENV["APP_SUB_DOMAIN"] || 'staging' %> # subdomain
port: 80
protocol: <%= ENV["APP_PROTOCOL"] || 'http' %>
assigns:
  mindmill_prefix: <%= ENV["MINDMILL_PREFIX"] || 'TTESTAG' %>
features:
  two_factor_enabled: <%= ENV['TWO_FACTOR_AUTHENTICATION_ENABLED'] %>
bulk_reports:
  size_limit: <%= ENV.fetch('BULK_REPORTS_ZIP_FILE_SIZE_LIMIT', 200_000_000).to_i %>
