domain: lvh.me
subdomain:
port: 31338
protocol: 'http'
assigns:
  mindmill_prefix: TTETEST
features:
  two_factor_enabled: <%= ENV['TWO_FACTOR_AUTHENTICATION_ENABLED'] %>
bulk_reports:
  size_limit: <%= ENV.fetch('BULK_REPORTS_ZIP_FILE_SIZE_LIMIT', 200_000_000).to_i %>
