apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ template "lighthouse.fullname" . }}-secret-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://kv-lh-uae-prod.vault.azure.net/"
      serviceAccountRef:
        name: lhprod-eso-app-sa

