apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "lighthouse.fullname" . }}-web
  creationTimestamp: null
  labels:
    app: {{ template "lighthouse.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ int .Values.web.replica }}
  selector:
    matchLabels:
      app: {{ template "lighthouse.fullname" . }}
      release: "{{ .Release.Name }}"
      role: web
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ template "lighthouse.fullname" . }}
        release: "{{ .Release.Name }}"
        role: web
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - args:
            - exec
            - falcon
            - host
          command:
            - bundle
          env:
            - name: PORT
              value: {{ .Values.services.internlPort | quote }}
          envFrom:
            - configMapRef:
                name: {{ template "lighthouse.fullname" . }}-env
            - secretRef:
                name: {{ template "lighthouse.fullname" . }}-eso-secrets
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: {{ .Chart.Name }}-web
          ports:
            - containerPort: {{ int .Values.services.internlPort }}
          livenessProbe:
            initialDelaySeconds: 50
            httpGet:
              path: /
              port: {{ int .Values.services.internlPort }}
              httpHeaders:
              - name: Host
                value: "{{ .Values.env.APP_SUB_DOMAIN }}.{{ .Values.env.APP_DOMAIN }}"
          readinessProbe:
            initialDelaySeconds: 50
            httpGet:
              path: /
              port: {{ int .Values.services.internlPort }}
              httpHeaders:
              - name: Host
                value: "{{ .Values.env.APP_SUB_DOMAIN }}.{{ .Values.env.APP_DOMAIN }}"
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
            {{- end }}
      terminationGracePeriodSeconds: 30
status: {}
