export const LABELS = {
  Least: 'At Least',
  LeastHotSpot: 'At Least',
  Most: 'At Most',
  Exact: 'Exactly',
  Range: 'Answers Range',
  RangeHotSpot: 'Answers Range',
  MinLength: 'Minimum characters',
  MaxLength: 'Maximum characters',
  CharacterRange: 'Character range',
  ContentValidation: 'Content Validation',
  MustRankAll: 'Must Rank All',
  MustTotal: 'Must Total',
  MustRankBetween: 'Must Rank Between',
  MustSelect: 'Must Select',
  EachGroupContains: 'Each Group Contains',
  Content: 'Content Validation',
  MinWords: 'Minimum words',
  MaxWords: 'Maximum words',
  WordsRange: 'Words range',
  NotInPast: 'Not In Past',
  NotInFuture: 'Not In Future',
}
