import {
  Checkbox, Descriptions, Form, Input, Typography, message,
} from 'antd'
import React, { useState } from 'react'
import * as t from 'io-ts'
import { FormInstance } from 'antd/es/form/Form'
import ResourceFormModal from '~/components/ResourceFormModal'
import userPresenter from '~/presenters/user'
import styles from './ResetPasswordModal.less'
import { useResources } from '~/hooks/useResources/useResources'

interface Props {
  close(): void
  user: {
    id: string
    email: string
    firstName: string
    lastName: string
  }
}

const { I18n } = window
const ResetPasswordTr = t.type({ id: t.string, password: t.union([t.string, t.null, t.undefined]), loginUrl: t.string })
type ResetPassword = t.TypeOf<typeof ResetPasswordTr>
type RequestFileds = {
  automaticallyGeneratePassword: boolean
  changePasswordOnLogin: boolean
  sendPasswordEmail: boolean
  password?: string
}
export const ResetPasswordModal: React.FC<Props> = ({ close, user }) => {
  const resource = useResources('users')
  const [autoGeneratedPassword, setAutoGeneratedPassword] = useState<string | null>(null)
  const [loginLinkloginUrl, setLoginLinkloginUrl] = useState<string>('')

  const handleSubmit = (values: RequestFileds) => resource.memberAction({
    action: 'reset_password',
    id: user.id,
    method: 'post',
    body: values,
    responseType: t.type({ id: t.string, password: t.union([t.string, t.null, t.undefined]) }),
  }).then(
    ({ password, loginUrl }: ResetPassword) => {
      if (password) {
        setAutoGeneratedPassword(password)
        setLoginLinkloginUrl(loginUrl)
      } else {
        close()
      }
      const message_key = values.sendPasswordEmail ? 'send_password_email_success' : 'reset_password_success'
      message.info(I18n.t(`reset_password_modal.messages.${message_key}`, { email: user.email }))
    },
  )

  return (
    <ResourceFormModal
      resourceName="users"
      readableResourceName="User"
      title={I18n.t('reset_password_modal.title')}
      close={close}
      manuallyClose
      scrollToFirstError
      modalProps={{ width: 620 }}
      hideOkButton={!!autoGeneratedPassword}
      submitButtonName={autoGeneratedPassword ? 'Done' : 'Reset'}
      request={{
        createResource: handleSubmit,
      }}
      formProps={{
        initialValues: {
          automaticallyGeneratePassword: true, changePasswordOnLogin: true, sendPasswordEmail: false,
        },
      }}
    >
      {({ form }) => {
        if (!autoGeneratedPassword) return <FormFields form={form} />

        return (
          <div className={styles.resetPasswordDetails}>
            <Typography.Title level={3}>{userPresenter.getFullName(user)}</Typography.Title>

            <Descriptions size="small">
              <Descriptions.Item label={I18n.t('reset_password_modal.fields.username')}>
                <Typography.Text copyable>{user.email}</Typography.Text>
              </Descriptions.Item>
            </Descriptions>

            <Descriptions size="small">
              <Descriptions.Item label={I18n.t('reset_password_modal.fields.new_password')}>
                <Typography.Text copyable>{autoGeneratedPassword}</Typography.Text>
              </Descriptions.Item>
            </Descriptions>

            <Descriptions size="small">
              <Descriptions.Item label={I18n.t('reset_password_modal.fields.login_link')}>
                <Typography.Text copyable={{ text: loginLinkloginUrl }}>
                  <a href={loginLinkloginUrl} target="_blank" rel="noreferrer">{loginLinkloginUrl}</a>
                </Typography.Text>
              </Descriptions.Item>
            </Descriptions>
          </div>
        )
      }}
    </ResourceFormModal>
  )
}

const FormFields: React.FC<{ form: FormInstance }> = ({ form }) => (
  <>
    <Form.Item name="automaticallyGeneratePassword" valuePropName="checked">
      <Checkbox>{I18n.t('reset_password_modal.fields.automatically_generate_password')}</Checkbox>
    </Form.Item>

    <Form.Item shouldUpdate noStyle>
      {() => {
        if (form.getFieldValue('automaticallyGeneratePassword')) { return null }
        return (
          <>
            <Form.Item name="password">
              <Input.Password placeholder={I18n.t('reset_password_modal.fields.password_placeholder')} />
            </Form.Item>
          </>
        )
      }}
    </Form.Item>

    <Form.Item name="changePasswordOnLogin" valuePropName="checked">
      <Checkbox>{I18n.t('reset_password_modal.fields.change_password_on_login')}</Checkbox>
    </Form.Item>

    <Form.Item name="sendPasswordEmail" valuePropName="checked">
      <Checkbox>{I18n.t('reset_password_modal.fields.send_password_email')}</Checkbox>
    </Form.Item>
  </>
)
