// Every table that stores a display preference is named here, most-general segment first, so a second table
// cannot quietly answer to the same key. A key drops its parent segment only when one table has two mount points.
export const TABLE_SETTINGS_KEYS = {
  adminAiAssistants: 'admin.ai_assistants',
  adminAssessments: 'admin.assessments',
  adminCampaignTemplates: 'admin.campaign_templates',
  adminDataReports: 'admin.data_reports',
  adminDevelopmentActions: 'admin.development_actions',
  adminDimensions: 'admin.dimensions',
  adminDimensionsDimensionFactors: 'admin.dimensions.dimension.factors',
  adminDimensionsDimensionInnovationStyles: 'admin.dimensions.dimension.innovation_styles',
  adminDimensionsDimensionOccupationConditionSets: 'admin.dimensions.dimension.occupation_condition_sets',
  adminDimensionsDimensionOccupations: 'admin.dimensions.dimension.occupations',
  adminDimensionsSubFactors: 'admin.dimensions.sub_factors',
  adminMediaLibrary: 'admin.media_library',
  adminNorms: 'admin.norms',
  adminNormsEditor: 'admin.norms.editor',
  adminQuestionCenterBlocks: 'admin.question_center.blocks',
  adminQuestionCenterQuestions: 'admin.question_center.questions',
  adminReportBundles: 'admin.report_bundles',
  adminReportBundlesBundleReports: 'admin.report_bundles.bundle.reports',
  adminReports: 'admin.reports',
  adminSkills: 'admin.skills',
  adminSkillsJobRoles: 'admin.skills.job_roles',
  adminSkillsProficiencyLevels: 'admin.skills.proficiency_levels',
  adminUsers: 'admin.users',
  adminUsersAdmins: 'admin.users.admins',
  adminUsersGlobalAssessors: 'admin.users.global_assessors',
  adminUsersSuperadmins: 'admin.users.superadmins',
  assessorCampaigns: 'assessor.campaigns',
  assessorParticipants: 'assessor.participants',
  campaignAiArtifactsSettings: 'campaign.ai_artifacts.settings',
  campaignParticipantsSmsContacts: 'campaign.participants.sms_contacts',
  campaignParticipantsSubjectAssessmentCenterInvites: 'campaign.participants.subject.assessment_center_invites',
  campaignParticipantsSubjectAssessmentCenters: 'campaign.participants.subject.assessment_centers',
  campaignParticipantsSubjectRecordings: 'campaign.participants.subject.recordings',
  campaignSchedulingAssessmentCenterActivities: 'campaign.scheduling.assessment_center.activities',
  campaignSchedulingAssessmentCenterParticipants: 'campaign.scheduling.assessment_center.participants',
  campaignSchedulingAssessmentCenterRecordings: 'campaign.scheduling.assessment_center.recordings',
  campaignSchedulingAssessmentCenterResources: 'campaign.scheduling.assessment_center.resources',
  campaignSchedulingAssessmentCenters: 'campaign.scheduling.assessment_centers',
  campaignSchedulingInvites: 'campaign.scheduling.invites',
  campaignSchedulingInvitesInviteAssessmentCenters: 'campaign.scheduling.invites.invite.assessment_centers',
  campaignSchedulingInvitesInviteParticipants: 'campaign.scheduling.invites.invite.participants',
  campaignSchedulingInvitesRequests: 'campaign.scheduling.invites.requests',
  clientDataReports: 'client.data_reports',
  clientLicenses: 'client.licenses',
  clientLicensesUsages: 'client.licenses.usages',
  clientSettingsAdminRoles: 'client.settings.admin_roles',
  clientSettingsSkillAliases: 'client.settings.skill_aliases',
  dataReportsJobs: 'data_reports.jobs',
  projectIdpInterviewQuestions: 'project.idp.interview_questions',
  projectIdpReflectionQuestions: 'project.idp.reflection_questions',
  projectIdpTemplates: 'project.idp.templates',
  projectLicenses: 'project.licenses',
  settingsApplications: 'settings.applications',
  settingsApplicationsApiKeys: 'settings.applications.api_keys',
  settingsApplicationsIpWhitelist: 'settings.applications.ip_whitelist',
  settingsApplicationsPublicKeys: 'settings.applications.public_keys',
  settingsApplicationsUrlWhitelist: 'settings.applications.url_whitelist',
} as const

export type TableSettingsKey = typeof TABLE_SETTINGS_KEYS[keyof typeof TABLE_SETTINGS_KEYS]
