#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

./node_modules/eslint/bin/eslint.js --ext .js,.jsx,.ts,.tsx app/frontend/ --max-warnings=0 --cache && bundle exec rubocop && bundle exec i18n-tasks unused
