#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'
require 'open3'

# Parse command line arguments
# Supports: script.rb <PR_NUMBER> [NEW_KEYS_JSON | --file <path>] [PR_URL] [TRANSLATION_BRANCH]
pr_number = ARGV[0]
new_keys_json = '[]'
pr_url = ''
translation_branch = ''

if pr_number.nil?
  warn "Usage: #{$PROGRAM_NAME} <PR_NUMBER> [NEW_KEYS_JSON | --file <path>] [PR_URL] [TRANSLATION_BRANCH]"
  exit 1
end

# Parse remaining arguments
i = 1
while i < ARGV.length
  if ARGV[i] == '--file' && ARGV[i + 1]
    file_path = ARGV[i + 1]
    if File.exist?(file_path)
      new_keys_json = File.read(file_path).strip
    else
      warn "Warning: File not found: #{file_path}, using empty array"
    end
    i += 2
  else
    if pr_url.empty?
      # First non-file argument after PR_NUMBER is either NEW_KEYS_JSON or PR_URL
      if ARGV[i]&.start_with?('[', '{')
        new_keys_json = ARGV[i] || '[]'
      else
        pr_url = ARGV[i] || ''
      end
    elsif translation_branch.empty?
      translation_branch = ARGV[i] || ''
    end
    i += 1
  end
end

# Helper method to run GitHub CLI commands
def run_gh_command(command)
  stdout, stderr, status = Open3.capture3(command)

  unless status.success?
    warn "GitHub CLI command failed: #{command}"
    warn "STDERR: #{stderr}" unless stderr.empty?
    exit 1
  end

  stdout.strip
end

begin
  # Parse the new keys JSON to get count
  new_keys_data = JSON.parse(new_keys_json)
  new_keys_count = new_keys_data.length

  # Determine comment based on whether keys were found and translations were generated
  if new_keys_count.positive? && !pr_url.empty?
    comment_body = <<~COMMENT
      ## 🤖 Translation Bot Results

      ✅ **Translations Generated Successfully!**

      - **New translation keys detected**: #{new_keys_count}
      - **Translation PR created**: #{pr_url}
      - **Branch**: `#{translation_branch}`
      - **Translation format**: Placeholder (`[LOCALE] English text`)
      - **Processing tool**: Ruby (YAML processor)

      ---
      Generated by Translation Bot 🌐 using Ruby
    COMMENT
  else
    comment_body = <<~COMMENT
      ## 🤖 Translation Bot Results

      ℹ️ **No new translation keys detected**

      The Translation Bot scanned this PR but didn't find any new English translation keys that need translation.

      ---
      Generated by Translation Bot 🌐 using Ruby
    COMMENT
  end

  # Create comment using GitHub CLI
  puts "Creating comment on PR ##{pr_number}..."

  # Escape the comment body for shell
  escaped_body = comment_body.gsub("'", "'\"'\"'")

  gh_command = "gh pr comment #{pr_number} --body '#{escaped_body}'"
  run_gh_command(gh_command)

  puts "Comment created successfully on PR ##{pr_number}"
rescue JSON::ParserError => e
  warn "Failed to parse new keys JSON: #{e.message}"

  # Fallback comment for JSON parse error
  comment_body = <<~COMMENT
    ## 🤖 Translation Bot Results

    ⚠️ **Processing Error**

    The Translation Bot encountered an error while processing this PR. Please check the workflow logs for more details.

    ---
    Generated by Translation Bot 🌐 using Ruby
  COMMENT

  escaped_body = comment_body.gsub("'", "'\"'\"'")
  gh_command = "gh pr comment #{pr_number} --body '#{escaped_body}'"
  run_gh_command(gh_command)

  exit 1
rescue StandardError => e
  warn "Error creating comment: #{e.message}"
  warn e.backtrace.join("\n")
  exit 1
end
