#!/usr/bin/env ruby
# frozen_string_literal: true

require 'open3'

# Parse command line arguments
# Usage: script.rb <PR_NUMBER> <CHANGES_MADE> [PR_URL] [TRANSLATION_BRANCH]
pr_number = ARGV[0]
changes_made = ARGV[1] == 'true'
pr_url = ARGV[2] || ''
translation_branch = ARGV[3] || ''

if pr_number.nil?
  warn "Usage: #{$PROGRAM_NAME} <PR_NUMBER> <CHANGES_MADE> [PR_URL] [TRANSLATION_BRANCH]"
  exit 1
end

# Helper method to run GitHub CLI commands
def run_gh_command(command)
  stdout, stderr, status = Open3.capture3(command)

  unless status.success?
    warn "GitHub CLI command failed: #{command}"
    warn "STDERR: #{stderr}" unless stderr.empty?
    exit 1
  end

  stdout.strip
end

# Determine comment based on whether translations were generated
comment_body = if changes_made && !pr_url.empty?
                 <<~COMMENT
                   ## 🤖 Translation Bot Results

                   ✅ **Translations Generated Successfully!**

                   - **Translation PR created**: #{pr_url}
                   - **Branch**: `#{translation_branch}`
                   - **Translation service**: Google Translate

                   ---
                   Generated by Translation Bot 🌐
                 COMMENT
               elsif changes_made
                 <<~COMMENT
                   ## 🤖 Translation Bot Results

                   ✅ **Translations Generated!**

                   Translation files were updated but PR creation may have failed. Please check the workflow logs.

                   ---
                   Generated by Translation Bot 🌐
                 COMMENT
               else
                 <<~COMMENT
                   ## 🤖 Translation Bot Results

                   ℹ️ **No translations needed**

                   The Translation Bot ran but no missing translations were found.

                   ---
                   Generated by Translation Bot 🌐
                 COMMENT
               end

# Create comment using GitHub CLI
puts "Creating comment on PR ##{pr_number}..."

# Escape the comment body for shell
escaped_body = comment_body.gsub("'", "'\"'\"'")

gh_command = "gh pr comment #{pr_number} --body '#{escaped_body}'"
run_gh_command(gh_command)

puts "Comment created successfully on PR ##{pr_number}"
