#!/usr/bin/env ruby
# frozen_string_literal: true

# Create a PR with generated translations
#
# Usage: create-translation-pr.rb <pr_number> <head_ref> <base_ref>
#
# Outputs (via GITHUB_OUTPUT):
#   pr_created        - "true" or "false"
#   pr_url            - URL of the created PR (if any)
#   translation_branch - Name of the translation branch

def write_output(key, value)
  github_output = ENV.fetch('GITHUB_OUTPUT', nil)
  return unless github_output

  File.open(github_output, 'a') { |f| f.puts "#{key}=#{value}" }
end

def run(cmd)
  output = `#{cmd}`.strip
  raise "Command failed: #{cmd}" unless $?.success?

  output
end

def run_silent(cmd)
  `#{cmd}`.strip
end

def configure_git
  run "git config --global user.name 'github-actions[bot]'"
  run "git config --global user.email 'github-actions[bot]@users.noreply.github.com'"
end

def has_changes?
  !system('git diff --quiet && git diff --cached --quiet')
end

def create_branch(pr_number)
  branch_name = "translations/pr-#{pr_number}-#{Time.now.to_i}"
  run "git checkout -b #{branch_name}"
  branch_name
end

def protected_branch?(branch_name)
  %w[develop review master].include?(branch_name)
end

def commit_translations(pr_number, head_ref, base_ref)
  run 'git add config/locales/'

  skip_ci_suffix = protected_branch?(base_ref) ? '' : ' [skip ci]'

  commit_message = <<~MSG
    Add translations for PR ##{pr_number}#{skip_ci_suffix}

    This commit contains AI generated translations for new English translation keys found in PR ##{pr_number}.

    Generated by: Translation Bot
    Source PR: ##{pr_number}
    Source Branch: #{head_ref}
  MSG

  run "git commit -m '#{commit_message.gsub("'", "\\'")}'"
end

def push_branch(branch_name)
  puts '→ Pushing branch to remote...'
  run "git push origin #{branch_name}"
end

def create_pr(pr_number, head_ref, base_ref, translation_branch)
  repo = ENV.fetch('GITHUB_REPOSITORY')

  title = "Add translations for PR ##{pr_number}"

  body = <<~BODY
    This PR contains AI generated translations for new English translation keys found in PR ##{pr_number}.

    ## 📝 Summary
    - **Source PR**: ##{pr_number}
    - **Original PR**: `#{head_ref}` → `#{base_ref}`
    - **Comparison Branch**: `#{base_ref}` (used for detecting new keys)
    - **Translation Target**: `#{head_ref}` (source branch of original PR)
    - **Generated by**: Translation Bot

    ---
    🤖 This PR was automatically created by the Translation Bot.
  BODY

  puts '→ Creating PR...'

  pr_url = run_silent(
    'gh pr create ' \
    "--title '#{title}' " \
    "--body '#{body.gsub("'", "\\'")}' " \
    "--base '#{head_ref}' " \
    "--head '#{translation_branch}' " \
    "--repo '#{repo}'"
  )

  pr_url.empty? ? nil : pr_url
end

def main
  pr_number = ARGV[0]
  head_ref = ARGV[1]
  base_ref = ARGV[2]

  if [pr_number, head_ref, base_ref].any?(&:nil?)
    warn "Usage: #{$PROGRAM_NAME} <pr_number> <head_ref> <base_ref>"
    exit 1
  end

  puts "→ Creating translation PR for PR ##{pr_number}"
  puts "  Head ref: #{head_ref}"
  puts "  Base ref: #{base_ref}"

  configure_git
  translation_branch = create_branch(pr_number)

  unless has_changes?
    puts '→ No changes to commit'
    write_output('pr_created', 'false')
    write_output('pr_url', '')
    write_output('translation_branch', translation_branch)
    exit 0
  end

  commit_translations(pr_number, head_ref, base_ref)
  push_branch(translation_branch)

  pr_url = create_pr(pr_number, head_ref, base_ref, translation_branch)

  if pr_url
    puts "→ PR created successfully: #{pr_url}"
    write_output('pr_created', 'true')
    write_output('pr_url', pr_url)
  else
    puts '→ Failed to create PR'
    write_output('pr_created', 'false')
    write_output('pr_url', '')
  end

  write_output('translation_branch', translation_branch)
end

main
