#!/bin/bash
set -e

PR_NUMBER="$1"
HEAD_REF="$2"
BASE_REF="$3"

if [ -z "$PR_NUMBER" ] || [ -z "$HEAD_REF" ] || [ -z "$BASE_REF" ]; then
  echo "Usage: $0 <PR_NUMBER> <HEAD_REF> <BASE_REF>" >&2
  exit 1
fi

echo "Creating translation PR for PR #$PR_NUMBER"
echo "Head ref: $HEAD_REF"
echo "Base ref: $BASE_REF"

# Configure git
git config --global user.name "github-actions[bot]"
git config --global user.email "github-actions[bot]@users.noreply.github.com"

# Create a new branch for translations
TRANSLATION_BRANCH="translations/pr-${PR_NUMBER}-$(date +%s)"
echo "Creating branch: $TRANSLATION_BRANCH"

git checkout -b "$TRANSLATION_BRANCH"

# Check if there are any changes to commit
if git diff --quiet && git diff --cached --quiet; then
  echo "No changes to commit"
  echo "pr_created=false" >> $GITHUB_OUTPUT
  echo "pr_url=" >> $GITHUB_OUTPUT
  echo "translation_branch=$TRANSLATION_BRANCH" >> $GITHUB_OUTPUT
  exit 0
fi

# Add and commit translation files
git add config/locales/
git commit -m "Add translations for PR #${PR_NUMBER}

This commit contains ai generated translations for new English translation keys found in PR #${PR_NUMBER}.

Generated by: Translation Bot (using Ruby)
Source PR: #${PR_NUMBER}
Source Branch: ${HEAD_REF}"

# Push the branch
echo "Pushing branch to remote..."
git push origin "$TRANSLATION_BRANCH"

# Create PR using GitHub CLI
PR_TITLE="Add translations for PR #${PR_NUMBER}"
PR_BODY="This PR contains ai generated translations for new English translation keys found in PR #${PR_NUMBER}.

## 📝 Summary
- **Source PR**: #${PR_NUMBER}
- **Original PR**: \`${HEAD_REF}\` → \`${BASE_REF}\`
- **Comparison Branch**: \`${BASE_REF}\` (used for detecting new keys)
- **Translation Target**: \`${HEAD_REF}\` (source branch of original PR)
- **Generated by**: Translation Bot (using Ruby)

---
🤖 This PR was automatically created by the Translation Bot using Ruby for YAML processing."

echo "Creating PR..."
NEW_PR_URL=$(gh pr create \
  --title "$PR_TITLE" \
  --body "$PR_BODY" \
  --base "$HEAD_REF" \
  --head "$TRANSLATION_BRANCH" \
  --repo "$GITHUB_REPOSITORY" || echo "")

if [ -n "$NEW_PR_URL" ]; then
  echo "PR created successfully: $NEW_PR_URL"
  echo "pr_created=true" >> $GITHUB_OUTPUT
  echo "pr_url=$NEW_PR_URL" >> $GITHUB_OUTPUT
  echo "translation_branch=$TRANSLATION_BRANCH" >> $GITHUB_OUTPUT
else
  echo "Failed to create PR"
  echo "pr_created=false" >> $GITHUB_OUTPUT
  echo "pr_url=" >> $GITHUB_OUTPUT
  echo "translation_branch=$TRANSLATION_BRANCH" >> $GITHUB_OUTPUT
fi
