name: CI
on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 40
    env:
      RAILS_ENV: test
      REDIS_HOST: localhost
      REDIS_URL: redis://localhost:6379/1
      NODE_OPTIONS: --max-old-space-size=4096
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ci_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis
        ports:
        - 6379:6379
        options: --entrypoint redis-server

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4
      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install -j $(nproc) --retry 3  --without development

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.3
      - name: Find yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: JS package cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install packages
        run: |
          yarn install --pure-lockfile
      - name: Linters
        run: |
          node_modules/eslint/bin/eslint.js --ext .js,.jsx,.ts,.tsx app/frontend --max-warnings=0
          bundle exec rubocop
      - name: Setup Database
        run: |
          cp config/database.yml.sample config/database.yml
          cp config/application.yml.sample  config/application.yml
          bundle exec rake parallel:create
          bundle exec rake parallel:load_schema

      - name: Run Javascript Tests
        run: yarn test

      - name: Webpack compile cache
        uses: actions/cache@v1
        with:
          path: public/packs-test
          key: ${{ runner.os }}-webpack-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('app/frontend/**/*.*') }}
      - name: Webpack compile
        run: |
          if [[ ! -d public/packs-test ]]; then
            bundle exec rails webpacker:compile
          else
            echo "No need to compile assets. Asset fetched from cache."
          fi

      - name: Run RSpec
        run: EAGER_LOAD=1 bundle exec parallel_test spec -t rspec --runtime-log support/parallel_runtime_rspec.log

      - name: Upload test artifacts
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: capybara_screenshots
          path: tmp/capybara
